Bet: privatebet/misc.c File Reference
misc.c File Reference
#include "misc.h"
Functions
int32_t hexstr_to_str (char *input, char *output)
void str_to_hexstr (char *input, char *output)
Function Documentation
hexstr_to_str()
int32_t hexstr_to_str (char * input, char * output)
Definition at line 3 of file misc.c.
Referenced by bet_dcv_verify_tx(), bet_process_dispute(), bet_show_fail_history(), bet_show_success_history(), and chips_create_tx_from_tx_list().
str_to_hexstr()
void str_to_hexstr (char * input, char * output)
Definition at line 36 of file misc.c.
Referenced by bet_dcv_poker_winner(), and bet_player_handle_stack_info_resp().