Bet: privatebet/client.c File Reference
client.c File Reference
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include "../includes/cJSON.h"
#include "../includes/ppapi/c/pp_stdint.h"
#include "../log/macrologger.h"
#include "bet.h"
#include "cards777.h"
#include "client.h"
#include "commands.h"
#include "common.h"
#include "gfshare.h"
#include "network.h"
#include "payment.h"
#include "states.h"
#include "table.h"
#include "storage.h"
#include "cashier.h"
#include "misc.h"
#include "host.h"
Macros
#define _POSIX_C_SOURCE 200809L /* For pclose, popen, strdup */
#define LWS_PLUGIN_STATIC
Functions
void write_to_GUI (void *ptr)
void sg777_test (cJSON *data)
void player_lws_write (cJSON *data)
char * enc_share_str (char hexstr[177], struct enc_share x)
struct enc_share get_API_enc_share (cJSON *obj)
int32_t bet_bvv_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_bvv_join_init (struct privatebet_info *bet)
static cJSON * bet_player_fundchannel (char *channel_id)
int32_t bet_check_bvv_ready (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_bvv_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_bvv_backend_loop (void *_ptr)
int32_t bet_bvv_backend (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
bits256 bet_decode_card (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars, int32_t cardid)
int32_t ln_pay_invoice (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_player_betting_invoice (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_player_winner (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_player_bet_round (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void display_cards ()
int32_t bet_client_receive_share (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_player_ask_share (struct privatebet_info *bet, int32_t cardid, int32_t playerid, int32_t card_type)
int32_t bet_client_give_share (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_get_own_share (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_turn (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_ready (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_bvv_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_dcv_init (cJSON *dcv_info, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_find_channel_balance (char *uri)
static int32_t bet_check_player_stack (char *uri)
int32_t bet_client_join_res (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_join (cJSON *argjson, struct privatebet_info *bet)
static int32_t bet_player_process_player_join (cJSON *argjson)
static void bet_player_handle_invalid_method (char *method)
static void bet_player_withdraw_request ()
static void bet_player_withdraw (cJSON *argjson)
static void bet_player_wallet_info ()
static void bet_player_process_be_status ()
int32_t bet_player_frontend (struct lws *wsi, cJSON *argjson)
static void bet_gui_init_message (struct privatebet_info *bet)
int lws_callback_http_player_write (struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
int lws_callback_http_player_read (struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
int lws_callback_http_player (struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
void player_sigint_handler (int sig)
void player_sigint_handler_read (int sig)
void player_sigint_handler_write (int sig)
void bet_player_frontend_read_loop (void *_ptr)
void bet_player_frontend_write_loop (void *_ptr)
void bet_player_frontend_loop (void *_ptr)
void bet_push_client (cJSON *argjson)
static void bet_player_blinds_info ()
static void bet_push_join_info (cJSON *argjson)
static int32_t bet_player_handle_stack_info_resp (cJSON *argjson, struct privatebet_info *bet)
int32_t bet_player_stack_info_req (struct privatebet_info *bet)
static int32_t bet_player_process_payout_tx (cJSON *argjson)
static int32_t bet_player_process_game_info (cJSON *argjson)
static void bet_update_seat_info (cJSON *argjson)
int32_t bet_player_backend (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_player_backend_loop (void *_ptr)
int32_t bet_player_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
bits256 bet_get_deckid (int32_t player_id)
void rest_push_cards (struct lws *wsi, cJSON *argjson, int32_t this_playerID)
void rest_display_cards (cJSON *argjson, int32_t this_playerID)
cJSON * bet_get_available_dealers ()
Variables
struct lws * wsi_global_client = NULL
struct lws * wsi_global_client_write = NULL
int ws_connection_status = 0
int ws_connection_status_write = 0
struct lws * wsi_global_bvv = NULL
int32_t player_card_matrix [hand_size]
int32_t player_card_values [hand_size]
int32_t number_cards_drawn = 0
int32_t sharesflag [CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
int32_t data_exists = 0
char player_gui_data [8196]
struct deck_player_info player_info
struct deck_bvv_info bvv_info
int32_t no_of_shares = 0
int32_t player_cards [CARDS777_MAXCARDS]
int32_t no_of_player_cards = 0
int32_t player_id = 0
int32_t player_joined = 0
bits256 all_v_hash [CARDS777_MAXPLAYERS][CARDS777_MAXCARDS][CARDS777_MAXCARDS]
bits256 all_g_hash [CARDS777_MAXPLAYERS][CARDS777_MAXPLAYERS][CARDS777_MAXCARDS]
int32_t all_sharesflag [CARDS777_MAXPLAYERS][CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
int32_t all_player_card_values [CARDS777_MAXPLAYERS][hand_size]
int32_t all_number_cards_drawn [CARDS777_MAXPLAYERS]
int32_t all_no_of_player_cards [CARDS777_MAXPLAYERS]
bits256 all_playershares [CARDS777_MAXPLAYERS][CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
struct enc_share * all_g_shares [CARDS777_MAXPLAYERS]
struct privatebet_info * bet_bvv = NULL
struct privatebet_vars * bvv_vars = NULL
struct privatebet_info * BET_player [CARDS777_MAXPLAYERS] = { NULL }
struct deck_player_info all_players_info [CARDS777_MAXPLAYERS]
char lws_buf_1 [65536]
int32_t lws_buf_length_1 = 0
char lws_buf_bvv [2000]
int32_t lws_buf_length_bvv = 0
char req_identifier [65]
int32_t backend_status = 0
int32_t sitout_value = 0
int32_t reset_lock = 0
struct lws_context_creation_info lws_player_info lws_player_info_read lws_player_info_write
struct lws_context * player_context = NULL
struct lws_context * player_context_read = NULL
struct lws_context * player_context_write = NULL
static struct lws_protocols player_http_protocol []
static struct lws_protocols player_http_protocol_read []
static struct lws_protocols player_http_protocol_write []
static int interrupted1
static int interrupted_read
static int interrupted_write
static const struct lws_http_mount lws_http_mount_player
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L /* For pclose, popen, strdup */
Definition at line 15 of file client.c.
LWS_PLUGIN_STATIC
#define LWS_PLUGIN_STATIC
Definition at line 39 of file client.c.
Function Documentation
bet_bvv_backend()
int32_t bet_bvv_backend (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 325 of file client.c.
References bet_bvv_init(), bet_bvv_join_init(), bet_bvv_reset(), bet_check_bvv_ready(), chips_tx_fee, max_players, privatebet_info::maxplayers, and table_stack_in_chips.
Referenced by bet_bvv_backend_loop().
bet_bvv_backend_loop()
void bet_bvv_backend_loop (void * _ptr)
Definition at line 293 of file client.c.
References bet_bvv_backend(), bet_bvv_join_init(), bet_bvv_reset(), bet_permutation(), bvv_info, bvv_state, bvv_vars, deck_bvv_info::permis, permis_b, privatebet_info::pushsock, privatebet_info::range, and privatebet_info::subsock.
Referenced by bet_bvv_thrd().
bet_bvv_init()
int32_t bet_bvv_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 158 of file client.c.
References bvv_info, deck_bvv_info::bvv_key, enc_share::bytes, CARDS777_MAXCARDS, CARDS777_MAXPLAYERS, deck_bvv_info::deckid, enc_share_str(), g_shares, privatebet_info::maxplayers, deck_bvv_info::maxplayers, privatebet_info::numplayers, deck_bvv_info::numplayers, p2p_bvv_init(), pair256::priv, pair256::prod, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_bvv_backend().
bet_bvv_join_init()
static int32_t bet_bvv_join_init (struct privatebet_info * bet) static
Definition at line 218 of file client.c.
References enc_share::bytes, and privatebet_info::pushsock.
Referenced by bet_bvv_backend(), and bet_bvv_backend_loop().
bet_bvv_reset()
void bet_bvv_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 283 of file client.c.
References bet_permutation(), bvv_info, g_shares, deck_bvv_info::permis, permis_b, and privatebet_info::range.
Referenced by bet_bvv_backend(), bet_bvv_backend_loop(), and bet_process_find_bvv().
bet_check_bvv_ready()
int32_t bet_check_bvv_ready (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 264 of file client.c.
References enc_share::bytes, and privatebet_info::pushsock.
Referenced by bet_bvv_backend().
bet_check_player_stack()
static int32_t bet_check_player_stack (char * uri) static
Definition at line 942 of file client.c.
References bet_find_channel_balance(), and table_stack.
bet_client_bvv_init()
int32_t bet_client_bvv_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 823 of file client.c.
References bet_player_ready(), deck_player_info::bvvblindcards, deck_player_info::bvvpubkey, enc_share::bytes, deck_player_info::cardprods, CARDS777_MAXCARDS, CARDS777_MAXPLAYERS, g_shares, get_API_enc_share(), privatebet_info::myplayerid, privatebet_info::numplayers, player_info, deck_player_info::player_key, pair256::priv, privatebet_info::range, v_hash, and xoverz_donna().
Referenced by bet_player_backend().
bet_client_dcv_init()
int32_t bet_client_dcv_init (cJSON * dcv_info, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 864 of file client.c.
References deck_player_info::cardprods, dcv_info, deck_player_info::deckid, g_hash, privatebet_info::numplayers, player_info, and privatebet_info::range.
Referenced by bet_player_backend().
bet_client_give_share()
int32_t bet_client_give_share (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 707 of file client.c.
References bet_decrypt(), deck_player_info::bvvpubkey, enc_share::bytes, g_shares, privatebet_info::myplayerid, privatebet_info::numplayers, player_info, deck_player_info::player_key, pair256::priv, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_player_backend().
bet_client_init()
int32_t bet_client_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 888 of file client.c.
References enc_share::bytes, deck_player_info::cardpubkeys, privatebet_info::myplayerid, player_info, deck_player_info::player_key, pair256::prod, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_player_backend().
bet_client_join()
int32_t bet_client_join (cJSON * argjson, struct privatebet_info * bet)
Definition at line 1030 of file client.c.
References enc_share::bytes, deck_player_info::cardprivkeys, deck_player_info::cardpubkeys, deckgen_player(), make_command(), deck_player_info::permis, player_info, deck_player_info::player_key, pair256::prod, privatebet_info::pushsock, privatebet_info::range, and req_identifier.
Referenced by bet_player_process_player_join().
bet_client_join_res()
int32_t bet_client_join_res (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 956 of file client.c.
References bet_player, enc_share::bytes, CHANNELD_AWAITING_LOCKIN, CHANNELD_NORMAL, ln_check_if_address_isof_type(), ln_check_peer_and_connect(), ln_establish_channel(), ln_get_channel_status(), ln_uri_length, privatebet_info::myplayerid, privatebet_vars::player_funds, player_info, deck_player_info::player_key, player_lws_write(), pair256::prod, and privatebet_info::pushsock.
Referenced by bet_player_backend().
bet_client_receive_share()
int32_t bet_client_receive_share (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 634 of file client.c.
References bet_decode_card(), privatebet_info::maxplayers, privatebet_info::myplayerid, no_of_shares, number_cards_drawn, deck_player_info::permis, player_card_values, player_info, playershares, privatebet_info::pushsock, privatebet_info::range, and sharesflag.
Referenced by bet_player_backend().
bet_client_turn()
int32_t bet_client_turn (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 780 of file client.c.
References bet_get_own_share(), bet_player_ask_share(), privatebet_info::myplayerid, no_of_shares, privatebet_info::numplayers, and sharesflag.
Referenced by bet_player_backend().
bet_decode_card()
bits256 bet_decode_card (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars, int32_t cardid)
Definition at line 351 of file client.c.
References deck_player_info::bvvblindcards, deck_player_info::cardprivkeys, deck_player_info::cardprods, crecip_donna(), curve25519_fieldelement(), deck_player_info::deckid, fmul_donna(), g_hash, gfshare_calc_sharenrs(), gfshare_recoverdata(), privatebet_info::maxplayers, privatebet_info::myplayerid, no_of_player_cards, player_cards, player_info, deck_player_info::player_key, playershares, pair256::priv, privatebet_info::range, sharenrs, v_hash, and xoverz_donna().
Referenced by bet_client_receive_share().
bet_find_channel_balance()
static int32_t bet_find_channel_balance (char * uri) static
Definition at line 915 of file client.c.
References make_command().
Referenced by bet_check_player_stack().
bet_get_available_dealers()
cJSON* bet_get_available_dealers ()
Definition at line 1998 of file client.c.
References bet_msg_cashier_with_response_id(), no_of_notaries, notary_node_ips, notary_status, and unique_id.
Referenced by bet_pick_dealer().
bet_get_deckid()
bits256 bet_get_deckid (int32_t player_id)
Definition at line 1912 of file client.c.
References all_players_info, deck_player_info::deckid, and player_id.
bet_get_own_share()
int32_t bet_get_own_share (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 753 of file client.c.
References bet_decrypt(), deck_player_info::bvvpubkey, enc_share::bytes, g_shares, privatebet_info::myplayerid, privatebet_info::numplayers, player_info, deck_player_info::player_key, playershares, pair256::priv, privatebet_info::range, and sharesflag.
Referenced by bet_client_turn().
bet_gui_init_message()
static void bet_gui_init_message (struct privatebet_info * bet) static
Definition at line 1224 of file client.c.
References backend_not_ready, backend_status, player_lws_write(), privatebet_info::pushsock, and req_identifier.
Referenced by lws_callback_http_player(), and lws_callback_http_player_write().
bet_player_ask_share()
static int32_t bet_player_ask_share (struct privatebet_info * bet, int32_t cardid, int32_t playerid, int32_t card_type) static
Definition at line 687 of file client.c.
References privatebet_info::pushsock.
Referenced by bet_client_turn().
bet_player_backend()
int32_t bet_player_backend (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1672 of file client.c.
References backend_status, bet_client_bvv_init(), bet_client_dcv_init(), bet_client_give_share(), bet_client_init(), bet_client_join_res(), bet_client_receive_share(), bet_client_turn(), bet_display_current_state(), bet_player_bet_round(), bet_player_betting_invoice(), bet_player_betting_statemachine(), bet_player_blinds_info(), bet_player_create_invoice(), bet_player_dealer_info(), bet_player_handle_stack_info_resp(), bet_player_process_game_info(), bet_player_process_payout_tx(), bet_player_reset(), bet_player_winner(), bet_push_join_info(), bet_update_seat_info(), chips_sign_raw_tx_with_wallet(), deck_player_info::deckid, privatebet_vars::funds, ln_listfunds(), ln_pay_invoice(), privatebet_info::myplayerid, privatebet_vars::player_funds, player_info, player_lws_write(), privatebet_info::pushsock, req_identifier, and reset_lock.
Referenced by bet_player_backend_loop().
bet_player_backend_loop()
void bet_player_backend_loop (void * _ptr)
Definition at line 1840 of file client.c.
References bet_player_backend(), bet_player_stack_info_req(), player_vars, privatebet_info::pushsock, and privatebet_info::subsock.
Referenced by bet_player_thrd().
bet_player_bet_round()
static int32_t bet_player_bet_round (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 577 of file client.c.
References bet_amount, privatebet_info::myplayerid, privatebet_info::pushsock, and privatebet_vars::round.
Referenced by bet_player_backend().
bet_player_betting_invoice()
static int32_t bet_player_betting_invoice (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 472 of file client.c.
References make_command(), privatebet_info::myplayerid, player_id, and privatebet_info::pushsock.
Referenced by bet_player_backend().
bet_player_blinds_info()
static void bet_player_blinds_info () static
Definition at line 1494 of file client.c.
References big_blind_amount, player_lws_write(), and small_blind_amount.
Referenced by bet_player_backend().
bet_player_frontend()
int32_t bet_player_frontend (struct lws * wsi, cJSON * argjson)
Definition at line 1185 of file client.c.
References bet_get_chips_ln_addr_info(), bet_get_chips_ln_bal_info(), bet_player, bet_player_handle_invalid_method(), bet_player_process_be_status(), bet_player_process_player_join(), bet_player_reset(), bet_player_round_betting(), bet_player_wallet_info(), bet_player_withdraw(), bet_player_withdraw_request(), player_lws_write(), player_vars, and sitout_value.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), and lws_callback_http_player_write().
bet_player_frontend_loop()
void bet_player_frontend_loop (void * _ptr)
Definition at line 1461 of file client.c.
References interrupted1, lws_http_mount_player, player_context, and player_http_protocol.
Referenced by bet_player_thrd().
bet_player_frontend_read_loop()
void bet_player_frontend_read_loop (void * _ptr)
Definition at line 1418 of file client.c.
References interrupted1, lws_http_mount_player, player_context_read, and player_http_protocol_read.
Referenced by bet_player_thrd().
bet_player_frontend_write_loop()
void bet_player_frontend_write_loop (void * _ptr)
Definition at line 1439 of file client.c.
References interrupted1, lws_http_mount_player, lws_player_info_write, player_context_write, and player_http_protocol_write.
Referenced by bet_player_thrd().
bet_player_fundchannel()
static cJSON* bet_player_fundchannel (char * channel_id) static
Definition at line 236 of file client.c.
References channel_fund_satoshis, and make_command().
bet_player_handle_invalid_method()
static void bet_player_handle_invalid_method (char * method) static
Definition at line 1119 of file client.c.
References player_lws_write().
Referenced by bet_player_frontend().
bet_player_handle_stack_info_resp()
static int32_t bet_player_handle_stack_info_resp (cJSON * argjson, struct privatebet_info * bet) static
Definition at line 1517 of file client.c.
References bet_msg_cashier(), bet_run_query(), chips_get_balance(), chips_get_block_hash_from_txid(), chips_get_block_height_from_block_hash(), chips_get_new_address(), chips_transfer_funds_with_data(), chips_tx_fee, legacy_m_of_n_msig_addr, max_players, privatebet_info::maxplayers, privatebet_info::pushsock, req_identifier, sql_query_size, str_to_hexstr(), table_id, table_stack_in_chips, threshold_value, tx_data_size, and tx_unspent.
Referenced by bet_player_backend().
bet_player_process_be_status()
static void bet_player_process_be_status () static
Definition at line 1175 of file client.c.
References backend_status, and player_lws_write().
Referenced by bet_player_frontend().
bet_player_process_game_info()
static int32_t bet_player_process_game_info (cJSON * argjson) static
Definition at line 1642 of file client.c.
References arg_size, bet_alloc_args(), bet_dealloc_args(), bet_make_insert_query(), bet_run_query(), and table_id.
Referenced by bet_player_backend().
bet_player_process_payout_tx()
static int32_t bet_player_process_payout_tx (cJSON * argjson) static
Definition at line 1627 of file client.c.
References bet_run_query().
Referenced by bet_player_backend().
bet_player_process_player_join()
static int32_t bet_player_process_player_join (cJSON * argjson) static
Definition at line 1100 of file client.c.
References backend_not_ready, backend_status, bet_client_join(), bet_player, player_joined, and player_lws_write().
Referenced by bet_player_frontend().
bet_player_ready()
int32_t bet_player_ready (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 806 of file client.c.
References enc_share::bytes, privatebet_info::myplayerid, player_ready, and privatebet_info::pushsock.
Referenced by bet_client_bvv_init().
bet_player_reset()
int32_t bet_player_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1875 of file client.c.
References privatebet_vars::bet_actions, bet_player_stack_info_req(), privatebet_vars::betamount, CARDS777_MAXROUNDS, hand_size, privatebet_info::maxplayers, no_of_player_cards, no_of_shares, number_cards_drawn, privatebet_info::numplayers, player_card_matrix, player_card_values, player_joined, privatebet_vars::pot, privatebet_info::range, req_identifier, reset_lock, sharesflag, and sitout_value.
Referenced by bet_player_backend(), and bet_player_frontend().
bet_player_stack_info_req()
int32_t bet_player_stack_info_req (struct privatebet_info * bet)
Definition at line 1606 of file client.c.
References chips_get_new_address(), privatebet_info::pushsock, and req_identifier.
Referenced by bet_player_backend_loop(), and bet_player_reset().
bet_player_wallet_info()
static void bet_player_wallet_info () static
Definition at line 1157 of file client.c.
References backend_status, chips_get_balance(), chips_get_wallet_address(), chips_tx_fee, max_players, normalization_factor, player_lws_write(), satoshis, satoshis_per_unit, table_id, and table_stack_in_chips.
Referenced by bet_player_frontend().
bet_player_winner()
static int32_t bet_player_winner (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 531 of file client.c.
References deck_player_info::deckid, make_command(), privatebet_info::myplayerid, player_info, and privatebet_info::pushsock.
Referenced by bet_player_backend().
bet_player_withdraw()
static void bet_player_withdraw (cJSON * argjson) static
Definition at line 1143 of file client.c.
References chips_transfer_funds(), and player_lws_write().
Referenced by bet_player_frontend().
bet_player_withdraw_request()
static void bet_player_withdraw_request () static
Definition at line 1131 of file client.c.
References chips_get_balance(), chips_list_address_groupings(), chips_tx_fee, and player_lws_write().
Referenced by bet_player_frontend().
bet_push_client()
void bet_push_client (cJSON * argjson)
Definition at line 1489 of file client.c.
References player_lws_write().
Referenced by bet_player_dealer_info(), and bet_player_round_betting_response().
bet_push_join_info()
static void bet_push_join_info (cJSON * argjson) static
Definition at line 1505 of file client.c.
References player_lws_write().
Referenced by bet_player_backend().
bet_update_seat_info()
static void bet_update_seat_info (cJSON * argjson) static
Definition at line 1661 of file client.c.
References player_lws_write().
Referenced by bet_player_backend().
display_cards()
void display_cards ()
Definition at line 603 of file client.c.
References hand_size, no_of_hole_cards, number_cards_drawn, player_card_values, and player_lws_write().
Referenced by bet_player_betting_statemachine().
enc_share_str()
char* enc_share_str (char hexstr[177], struct enc_share x)
Definition at line 138 of file client.c.
References enc_share::bytes.
Referenced by bet_bvv_init().
get_API_enc_share()
struct enc_share get_API_enc_share (cJSON * obj)
Definition at line 138 of file client.c.
Referenced by bet_client_bvv_init().
ln_pay_invoice()
int32_t ln_pay_invoice (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 426 of file client.c.
References make_command(), privatebet_info::myplayerid, and player_id.
Referenced by bet_player_backend(), and bet_player_paymentloop().
lws_callback_http_player()
int lws_callback_http_player (struct lws * wsi, enum lws_callback_reasons reason, void * user, void * in, size_t len)
Definition at line 1325 of file client.c.
References bet_gui_init_message(), bet_player, bet_player_frontend(), data_exists, lws_buf_1, lws_buf_length_1, player_gui_data, ws_connection_status, and wsi_global_client.
lws_callback_http_player_read()
int lws_callback_http_player_read (struct lws * wsi, enum lws_callback_reasons reason, void * user, void * in, size_t len)
Definition at line 1286 of file client.c.
References bet_player_frontend(), data_exists, lws_buf_1, lws_buf_length_1, player_gui_data, ws_connection_status, and wsi_global_client.
lws_callback_http_player_write()
int lws_callback_http_player_write (struct lws * wsi, enum lws_callback_reasons reason, void * user, void * in, size_t len)
Definition at line 1246 of file client.c.
References bet_gui_init_message(), bet_player, bet_player_frontend(), data_exists, lws_buf_1, lws_buf_length_1, player_gui_data, ws_connection_status_write, and wsi_global_client_write.
player_lws_write()
void player_lws_write (cJSON * data)
Definition at line 121 of file client.c.
References backend_status, data_exists, player_gui_data, ws_connection_status_write, and wsi_global_client_write.
Referenced by bet_client_join_res(), bet_gui_init_message(), bet_player_backend(), bet_player_betting_statemachine(), bet_player_big_blind(), bet_player_blinds_info(), bet_player_frontend(), bet_player_handle_invalid_method(), bet_player_process_be_status(), bet_player_process_player_join(), bet_player_small_blind(), bet_player_wallet_info(), bet_player_withdraw(), bet_player_withdraw_request(), bet_push_client(), bet_push_join_info(), bet_update_seat_info(), and display_cards().
player_sigint_handler()
void player_sigint_handler (int sig)
Definition at line 1403 of file client.c.
References interrupted1.
player_sigint_handler_read()
void player_sigint_handler_read (int sig)
Definition at line 1408 of file client.c.
References interrupted_read.
player_sigint_handler_write()
void player_sigint_handler_write (int sig)
Definition at line 1413 of file client.c.
References interrupted_write.
rest_display_cards()
void rest_display_cards (cJSON * argjson, int32_t this_playerID)
Definition at line 1952 of file client.c.
References action_str, all_number_cards_drawn, all_player_card_values, BET_player, big_blind_amount, face, hand_size, privatebet_info::maxplayers, NFACES, no_of_hole_cards, NSUITS, small_blind_amount, and suit.
rest_push_cards()
void rest_push_cards (struct lws * wsi, cJSON * argjson, int32_t this_playerID)
Definition at line 1917 of file client.c.
References all_number_cards_drawn, all_player_card_values, hand_size, and no_of_hole_cards.
sg777_test()
void sg777_test (cJSON * data)
Definition at line 108 of file client.c.
References write_to_GUI().
write_to_GUI()
void write_to_GUI (void * ptr)
Definition at line 95 of file client.c.
References data_exists, player_gui_data, ws_connection_status, and wsi_global_client.
Referenced by sg777_test().
Variable Documentation
all_g_hash
bits256 all_g_hash[CARDS777_MAXPLAYERS][CARDS777_MAXPLAYERS][CARDS777_MAXCARDS]
Definition at line 66 of file client.c.
all_g_shares
struct enc_share* all_g_shares[CARDS777_MAXPLAYERS]
Definition at line 74 of file client.c.
all_no_of_player_cards
int32_t all_no_of_player_cards[CARDS777_MAXPLAYERS]
Definition at line 71 of file client.c.
all_number_cards_drawn
int32_t all_number_cards_drawn[CARDS777_MAXPLAYERS]
Definition at line 70 of file client.c.
Referenced by rest_display_cards(), and rest_push_cards().
all_player_card_values
int32_t all_player_card_values[CARDS777_MAXPLAYERS][hand_size]
Definition at line 69 of file client.c.
Referenced by rest_display_cards(), and rest_push_cards().
all_players_info
struct deck_player_info all_players_info[CARDS777_MAXPLAYERS]
Definition at line 79 of file client.c.
Referenced by bet_get_deckid().
all_playershares
bits256 all_playershares[CARDS777_MAXPLAYERS][CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
Definition at line 72 of file client.c.
all_sharesflag
int32_t all_sharesflag[CARDS777_MAXPLAYERS][CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
Definition at line 67 of file client.c.
all_v_hash
bits256 all_v_hash[CARDS777_MAXPLAYERS][CARDS777_MAXCARDS][CARDS777_MAXCARDS]
Definition at line 65 of file client.c.
backend_status
int32_t backend_status = 0
Definition at line 88 of file client.c.
Referenced by bet_gui_init_message(), bet_player_backend(), bet_player_process_be_status(), bet_player_process_player_join(), bet_player_wallet_info(), and player_lws_write().
bet_bvv
struct privatebet_info* bet_bvv = NULL
Definition at line 76 of file client.c.
Referenced by bet_bvv_deinitialize(), bet_bvv_initialize(), bet_bvv_thrd(), and bet_process_find_bvv().
BET_player
struct privatebet_info* BET_player[CARDS777_MAXPLAYERS] = { NULL }
Definition at line 79 of file client.c.
Referenced by rest_display_cards().
bvv_info
struct deck_bvv_info bvv_info
Definition at line 54 of file client.c.
Referenced by bet_bvv_backend_loop(), bet_bvv_init(), bet_bvv_reset(), and find_bvv().
bvv_vars
struct privatebet_vars* bvv_vars = NULL
Definition at line 77 of file client.c.
Referenced by bet_bvv_backend_loop(), bet_bvv_deinitialize(), bet_bvv_initialize(), and bet_process_find_bvv().
data_exists
int32_t data_exists = 0
Definition at line 53 of file client.c.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), lws_callback_http_player_write(), player_lws_write(), and write_to_GUI().
interrupted1
int interrupted1 static
Definition at line 1381 of file client.c.
Referenced by bet_player_frontend_loop(), bet_player_frontend_read_loop(), bet_player_frontend_write_loop(), and player_sigint_handler().
interrupted_read
int interrupted_read static
Definition at line 1381 of file client.c.
Referenced by player_sigint_handler_read().
interrupted_write
int interrupted_write static
Definition at line 1381 of file client.c.
Referenced by player_sigint_handler_write().
lws_buf_1
char lws_buf_1[65536]
Definition at line 82 of file client.c.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), and lws_callback_http_player_write().
lws_buf_bvv
char lws_buf_bvv[2000]
Definition at line 84 of file client.c.
lws_buf_length_1
int32_t lws_buf_length_1 = 0
Definition at line 83 of file client.c.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), and lws_callback_http_player_write().
lws_buf_length_bvv
int32_t lws_buf_length_bvv = 0
Definition at line 85 of file client.c.
lws_http_mount_player
const struct lws_http_mount lws_http_mount_player static
Initial value:
= {
         NULL,
         "/",
         "./mount-origin",
         "index.html",
         NULL,
         NULL,
         NULL,
         NULL,
         0,
         0,
         0,
         0,
         0,
         0,
         LWSMPRO_FILE,
         1,
         NULL,
}
Definition at line 1381 of file client.c.
Referenced by bet_player_frontend_loop(), bet_player_frontend_read_loop(), and bet_player_frontend_write_loop().
lws_player_info_write
struct lws_context_creation_info lws_player_info lws_player_info_read lws_player_info_write
Definition at line 90 of file client.c.
Referenced by bet_player_frontend_write_loop().
no_of_player_cards
int32_t no_of_player_cards = 0
Definition at line 60 of file client.c.
Referenced by bet_decode_card(), and bet_player_reset().
no_of_shares
int32_t no_of_shares = 0
Definition at line 58 of file client.c.
Referenced by bet_client_receive_share(), bet_client_turn(), and bet_player_reset().
number_cards_drawn
int32_t number_cards_drawn = 0
Definition at line 49 of file client.c.
Referenced by bet_client_receive_share(), bet_player_reset(), and display_cards().
player_card_matrix
int32_t player_card_matrix[hand_size]
Definition at line 47 of file client.c.
Referenced by bet_player_reset().
player_card_values
int32_t player_card_values[hand_size]
Definition at line 48 of file client.c.
Referenced by bet_client_receive_share(), bet_player_reset(), and display_cards().
player_cards
int32_t player_cards[CARDS777_MAXCARDS]
Definition at line 59 of file client.c.
Referenced by bet_decode_card().
player_context
struct lws_context* player_context = NULL
Definition at line 93 of file client.c.
Referenced by bet_player_frontend_loop().
player_context_read
struct lws_context * player_context_read = NULL
Definition at line 93 of file client.c.
Referenced by bet_player_frontend_read_loop().
player_context_write
struct lws_context * player_context_write = NULL
Definition at line 93 of file client.c.
Referenced by bet_player_frontend_write_loop().
player_gui_data
char player_gui_data[8196]
Definition at line 54 of file client.c.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), lws_callback_http_player_write(), player_lws_write(), and write_to_GUI().
player_http_protocol
struct lws_protocols player_http_protocol[] static
Initial value:
= {
        { "http", lws_callback_http_player, 0, 0 },
        { NULL, NULL, 0, 0 }
}
Definition at line 1325 of file client.c.
Referenced by bet_player_frontend_loop().
player_http_protocol_read
struct lws_protocols player_http_protocol_read[] static
Initial value:
= {
        { "http", lws_callback_http_player_read, 0, 0 },
        { NULL, NULL, 0, 0 }
}
Definition at line 1325 of file client.c.
Referenced by bet_player_frontend_read_loop().
player_http_protocol_write
struct lws_protocols player_http_protocol_write[] static
Initial value:
= {
        { "http", lws_callback_http_player_write, 0, 0 },
        { NULL, NULL, 0, 0 }
}
Definition at line 1325 of file client.c.
Referenced by bet_player_frontend_write_loop().
player_id
int32_t player_id = 0
Definition at line 62 of file client.c.
Referenced by bet_get_deckid(), bet_player_betting_invoice(), and ln_pay_invoice().
player_info
struct deck_player_info player_info
Definition at line 54 of file client.c.
Referenced by bet_client_bvv_init(), bet_client_dcv_init(), bet_client_give_share(), bet_client_init(), bet_client_join(), bet_client_join_res(), bet_client_receive_share(), bet_decode_card(), bet_get_own_share(), bet_player_backend(), bet_player_join_req(), bet_player_winner(), bet_process_dispute(), and chips_create_tx_from_tx_list().
player_joined
int32_t player_joined = 0
Definition at line 63 of file client.c.
Referenced by bet_player_process_player_join(), and bet_player_reset().
req_identifier
char req_identifier[65]
Definition at line 87 of file client.c.
Referenced by bet_client_join(), bet_gui_init_message(), bet_player_backend(), bet_player_handle_stack_info_resp(), bet_player_reset(), and bet_player_stack_info_req().
reset_lock
int32_t reset_lock = 0
Definition at line 90 of file client.c.
Referenced by bet_player_backend(), and bet_player_reset().
sharesflag
int32_t sharesflag[CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
Definition at line 51 of file client.c.
Referenced by bet_client_receive_share(), bet_client_turn(), bet_get_own_share(), and bet_player_reset().
sitout_value
int32_t sitout_value = 0
Definition at line 89 of file client.c.
Referenced by bet_player_frontend(), and bet_player_reset().
ws_connection_status
int ws_connection_status = 0
Definition at line 43 of file client.c.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), and write_to_GUI().
ws_connection_status_write
int ws_connection_status_write = 0
Definition at line 43 of file client.c.
Referenced by lws_callback_http_player_write(), and player_lws_write().
wsi_global_bvv
struct lws* wsi_global_bvv = NULL
Definition at line 45 of file client.c.
wsi_global_client
struct lws* wsi_global_client = NULL
Definition at line 41 of file client.c.
Referenced by lws_callback_http_player(), lws_callback_http_player_read(), and write_to_GUI().
wsi_global_client_write
struct lws * wsi_global_client_write = NULL
Definition at line 41 of file client.c.
Referenced by lws_callback_http_player_write(), and player_lws_write().