Bet: privatebet/config.h File Reference
config.h File Reference
#include "bet.h"
Functions
cJSON * bet_read_json_file (char *file_name)
void bet_parse_dealer_config_file ()
void bet_parse_cashier_nodes_file ()
Function Documentation
bet_parse_cashier_nodes_file()
void bet_parse_cashier_nodes_file ()
Definition at line 63 of file config.c.
References bet_read_json_file(), no_of_notaries, notaries_file, notary_node_ips, notary_node_pubkeys, and notary_status.
Referenced by common_init().
bet_parse_dealer_config_file()
void bet_parse_dealer_config_file ()
Definition at line 48 of file config.c.
References bet_read_json_file(), chips_tx_fee, dealer_config_file, max_players, and table_stack_in_chips.
Referenced by dealer_node_init(), and main().
bet_read_json_file()
cJSON* bet_read_json_file (char * file_name)
Definition at line 7 of file config.c.
Referenced by bet_parse_cashier_nodes_file(), and bet_parse_dealer_config_file().