Bet: /root/bet/privatebet/cards777.h File Reference
cards777.h File Reference
Functions
int32_t bet_permutation (int32_t *permi, int32_t numcards)
int32_t bet_cipher_create (bits256 privkey, bits256 destpub, uint8_t *cipher, uint8_t *data, int32_t datalen)
uint8_t * bet_decrypt (uint8_t *decoded, int32_t maxsize, bits256 senderpub, bits256 mypriv, uint8_t *ptr, int32_t *recvlenp)
Function Documentation
bet_cipher_create()
int32_t bet_cipher_create (bits256 privkey, bits256 destpub, uint8_t * cipher, uint8_t * data, int32_t datalen)
Definition at line 62 of file cards777.c.
Referenced by p2p_bvv_init().
bet_decrypt()
uint8_t* bet_decrypt (uint8_t * decoded, int32_t maxsize, bits256 senderpub, bits256 mypriv, uint8_t * ptr, int32_t * recvlenp)
Definition at line 88 of file cards777.c.
Referenced by bet_client_give_share(), bet_get_own_share(), and BET_rest_player_get_own_share().
bet_permutation()
int32_t bet_permutation (int32_t * permi, int32_t numcards)
Definition at line 20 of file cards777.c.
References CARDS777_MAXCARDS.
Referenced by bet_bvv_backend_loop(), bet_bvv_reset(), bet_dcv_backend_loop(), bet_dcv_force_reset(), bet_dcv_reset(), and deckgen_player().