Bet: /root/bet/privatebet/network.h File Reference
network.h File Reference
#include "bet.h"
Functions
char * bet_tcp_sock_address (int32_t bindflag, char *str, char *ipaddr, uint16_t port)
int32_t bet_nanosock (int32_t bindflag, char *endpoint, int32_t nntype)
Function Documentation
bet_nanosock()
int32_t bet_nanosock (int32_t bindflag, char * endpoint, int32_t nntype)
Definition at line 29 of file network.c.
Referenced by bet_bvv_initialize(), bet_dcv_initialize(), and bet_player_initialize().
bet_tcp_sock_address()
char* bet_tcp_sock_address (int32_t bindflag, char * str, char * ipaddr, uint16_t port)
Definition at line 21 of file network.c.
Referenced by bet_bvv_initialize(), bet_dcv_initialize(), and bet_player_initialize().