Bet: /root/bet/privatebet/cashier.h File Reference
cashier.h File Reference
Functions
char * bet_check_notary_status ()
int32_t bet_send_status (struct cashier *cashier_info)
int32_t bet_cashier_backend (cJSON *argjson, struct cashier *cashier_info)
void bet_cashier_server_loop (void *_ptr)
void bet_cashier_client_loop (void *_ptr)
void bet_cashier_status_loop (void *_ptr)
int32_t bet_submit_msig_raw_tx (cJSON *tx)
Function Documentation
bet_cashier_backend()
int32_t bet_cashier_backend (cJSON * argjson, struct cashier * cashier_info)
Definition at line 107 of file cashier.c.
References bet_send_status(), cashier::c_pubsock, and chips_sign_raw_tx_with_wallet().
Referenced by bet_cashier_server_loop().
bet_cashier_client_loop()
void bet_cashier_client_loop (void * _ptr)
Definition at line 183 of file cashier.c.
References bet_cashier_client_backend(), cashier::c_pushsock, and cashier::c_subsock.
bet_cashier_server_loop()
void bet_cashier_server_loop (void * _ptr)
Definition at line 212 of file cashier.c.
References bet_cashier_backend(), cashier::c_pubsock, and cashier::c_pullsock.
Referenced by bet_cashier_server_thrd().
bet_cashier_status_loop()
void bet_cashier_status_loop (void * _ptr)
Definition at line 148 of file cashier.c.
References cashier::c_pushsock, cashier::c_subsock, and live_notaries.
Referenced by bet_check_notary_status().
bet_check_notary_status()
char* bet_check_notary_status ()
Definition at line 32 of file cashier.c.
References bet_cashier_status_loop(), bet_nanosock(), bet_tcp_sock_address(), cashier::c_pushsock, cashier::c_subsock, live_notaries, no_of_notaries, notary_node_ips, and notary_status.
Referenced by chips_spend_msig_txs().
bet_send_status()
int32_t bet_send_status (struct cashier * cashier_info)
Definition at line 93 of file cashier.c.
References cashier::c_pubsock.
Referenced by bet_cashier_backend(), and bet_cashier_client_backend().
bet_submit_msig_raw_tx()
int32_t bet_submit_msig_raw_tx (cJSON * tx)
Definition at line 242 of file cashier.c.
References cashier::c_pushsock.