Bet: /root/bet/privatebet/host.h File Reference
host.h File Reference
#include "bet.h"
Functions
int32_t bet_dcv_deck_init_info (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_start (struct privatebet_info *bet, int32_t peerid)
int32_t bet_player_join_req (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_turn (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_relay (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_check_player_ready (cJSON *playerReady, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_backend (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_dcv_backend_loop (void *_ptr)
int32_t bet_receive_card (cJSON *playerCardInfo, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_dcv_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_dcv_force_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_dcv_frontend_loop (void *_ptr)
void bet_dcv_live_loop (void *_ptr)
void bet_chat (struct lws *wsi, cJSON *argjson)
int32_t bet_seats (struct lws *wsi, cJSON *argjson)
int32_t bet_game (struct lws *wsi, cJSON *argjson)
int32_t bet_dcv_frontend (struct lws *wsi, cJSON *argjson)
int32_t bet_evaluate_hand (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_push_dcv_to_gui (cJSON *argjson)
void dcv_lws_write (cJSON *data)
Function Documentation
bet_chat()
void bet_chat (struct lws * wsi, cJSON * argjson)
Definition at line 91 of file host.c.
Referenced by bet_dcv_frontend().
bet_check_player_ready()
int32_t bet_check_player_ready (cJSON * playerReady, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 730 of file host.c.
References privatebet_info::maxplayers, and player_ready.
Referenced by bet_dcv_backend().
bet_dcv_backend()
int32_t bet_dcv_backend (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1279 of file host.c.
References bet_award_winner(), bet_check_bvv_ready(), bet_check_player_ready(), bet_create_betting_invoice(), bet_create_invoice(), bet_dcv_bvv_join(), bet_dcv_deck_init_info(), bet_dcv_init(), bet_dcv_start(), bet_dcv_turn(), bet_display_current_state(), bet_initiate_statemachine(), bet_ln_check(), bet_player_betting_statemachine(), bet_player_join_req(), bet_push_joinInfo(), bet_receive_card(), bet_relay(), bvv_status, chips_check_if_tx_unspent(), chips_create_tx_from_tx_list(), chips_get_block_count(), chips_publish_multisig_tx(), chips_send_raw_tx(), dcv_info, privatebet_vars::funds, is_signed, max_no_of_signers, privatebet_info::maxplayers, deck_dcv_info::maxplayers, no_of_signers, no_of_txs, notary_node_addrs, privatebet_info::numplayers, deck_dcv_info::numplayers, player_status, privatebet_info::pubsock, table_stack_in_chips, and tx_ids.
Referenced by bet_dcv_backend_loop().
bet_dcv_backend_loop()
void bet_dcv_backend_loop (void * _ptr)
Definition at line 1413 of file host.c.
References bet_dcv_backend(), bet_permutation(), card_matrix, card_values, dcv_info, deck_dcv_info::dcv_key, privatebet_vars::dealer, dealerPosition, deck_dcv_info::deckid, hand_size, invoiceID, privatebet_info::maxplayers, deck_dcv_info::maxplayers, mutex, deck_dcv_info::numplayers, deck_dcv_info::permis, permis_d, player_ready, pair256::priv, pair256::prod, privatebet_info::pubsock, privatebet_info::pullsock, and privatebet_info::range.
Referenced by bet_dcv_thrd().
bet_dcv_deck_init_info()
int32_t bet_dcv_deck_init_info (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 265 of file host.c.
References deck_dcv_info::cardprods, dcv_info, deck_dcv_info::dcvblindcards, deck_dcv_info::deckid, g_hash, deck_dcv_info::numplayers, deck_dcv_info::peerpubkeys, privatebet_info::pubsock, and privatebet_info::range.
Referenced by bet_dcv_backend().
bet_dcv_force_reset()
void bet_dcv_force_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 902 of file host.c.
References privatebet_vars::bet_actions, bet_permutation(), privatebet_vars::betamount, card_matrix, card_values, privatebet_info::cardid, CARDS777_MAXROUNDS, community_cards_drawn, dcv_info, deck_dcv_info::dcv_key, deck_dcv_info::deckid, flop_cards_drawn, privatebet_vars::funds, hand_size, hole_cards_drawn, invoiceID, privatebet_vars::last_raise, privatebet_vars::last_turn, privatebet_info::maxplayers, deck_dcv_info::maxplayers, no_of_bets, no_of_cards, no_of_rounds, privatebet_info::no_of_turns, privatebet_info::numplayers, deck_dcv_info::numplayers, deck_dcv_info::permis, permis_d, player_ready, players_joined, privatebet_vars::pot, pair256::priv, pair256::prod, privatebet_info::range, river_card_drawn, privatebet_vars::round, turn, turn_card_drawn, privatebet_info::turni, and privatebet_vars::turni.
Referenced by bet_dcv_frontend().
bet_dcv_frontend()
int32_t bet_dcv_frontend (struct lws * wsi, cJSON * argjson)
Definition at line 168 of file host.c.
References bet_chat(), bet_dcv_force_reset(), bet_game(), bet_seats(), and privatebet_info::pubsock.
Referenced by lws_callback_http_dummy().
bet_dcv_frontend_loop()
void bet_dcv_frontend_loop (void * _ptr)
Definition at line 1467 of file host.c.
References interrupted, mount, and protocols.
Referenced by bet_dcv_thrd().
bet_dcv_init()
int32_t bet_dcv_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 313 of file host.c.
References bet_dcv_start(), deck_dcv_info::cardprods, CARDS777_MAXCARDS, dcv_info, deck_dcv_info::dcvblindcards, deck_dcv_info::deckid, privatebet_info::maxplayers, deck_dcv_info::numplayers, privatebet_info::range, and sg777_deckgen_vendor().
Referenced by bet_dcv_backend().
bet_dcv_live_loop()
void bet_dcv_live_loop (void * _ptr)
Definition at line 1521 of file host.c.
References bet_live_status(), bvv_status, privatebet_info::maxplayers, player_status, and privatebet_info::pubsock.
Referenced by bet_dcv_thrd().
bet_dcv_reset()
void bet_dcv_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 841 of file host.c.
References privatebet_vars::bet_actions, bet_permutation(), bet_push_dcv_to_gui(), privatebet_vars::betamount, card_matrix, card_values, privatebet_info::cardid, CARDS777_MAXROUNDS, community_cards_drawn, dcv_info, deck_dcv_info::dcv_key, privatebet_vars::dealer, dealerPosition, deck_dcv_info::deckid, flop_cards_drawn, privatebet_vars::funds, hand_size, hole_cards_drawn, invoiceID, privatebet_vars::last_raise, privatebet_vars::last_turn, privatebet_info::maxplayers, deck_dcv_info::maxplayers, no_of_bets, no_of_cards, no_of_rounds, privatebet_info::no_of_turns, privatebet_info::numplayers, deck_dcv_info::numplayers, deck_dcv_info::permis, permis_d, player_ready, players_joined, privatebet_vars::pot, pair256::priv, pair256::prod, privatebet_info::range, river_card_drawn, privatebet_vars::round, turn, turn_card_drawn, privatebet_info::turni, and privatebet_vars::turni.
Referenced by bet_evaluate_hand().
bet_dcv_start()
int32_t bet_dcv_start (struct privatebet_info * bet, int32_t peerid)
Definition at line 419 of file host.c.
References privatebet_info::pubsock.
Referenced by bet_dcv_backend(), and bet_dcv_init().
bet_dcv_turn()
int32_t bet_dcv_turn (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 515 of file host.c.
References bet_send_turn_info(), card_matrix, flop_card_1, flop_card_2, flop_card_3, flop_cards_drawn, hole_card, hole_cards_drawn, privatebet_info::maxplayers, no_of_flop_cards, no_of_hole_cards, no_of_river_card, no_of_turn_card, river_card, river_card_drawn, turn_card, and turn_card_drawn.
Referenced by bet_dcv_backend(), bet_dcv_round_betting(), and bet_receive_card().
bet_evaluate_hand()
int32_t bet_evaluate_hand (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 954 of file host.c.
References privatebet_vars::bet_actions, bet_dcv_invoice_pay(), bet_dcv_reset(), card_values, CARDS777_MAXPLAYERS, fold, hand_size, privatebet_info::maxplayers, no_of_hole_cards, privatebet_vars::pot, privatebet_info::pubsock, privatebet_vars::round, seven_card_draw_score(), and wsi_global_host.
Referenced by bet_dcv_round_betting().
bet_game()
int32_t bet_game (struct lws * wsi, cJSON * argjson)
Definition at line 143 of file host.c.
References big_blind_amount, max_players, and small_blind_amount.
Referenced by bet_dcv_frontend().
bet_player_join_req()
int32_t bet_player_join_req (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 436 of file host.c.
References dcv_info, dealerPosition, make_command(), privatebet_info::numplayers, deck_dcv_info::peerpubkeys, player_info, players_joined, privatebet_info::pubsock, and deck_dcv_info::uri.
Referenced by bet_dcv_backend().
bet_push_dcv_to_gui()
void bet_push_dcv_to_gui (cJSON * argjson)
Definition at line 258 of file host.c.
References dcv_lws_write().
Referenced by bet_dcv_reset(), and bet_initiate_statemachine().
bet_receive_card()
int32_t bet_receive_card (cJSON * playerCardInfo, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 743 of file host.c.
References bet_dcv_round_betting(), bet_dcv_small_blind(), bet_dcv_turn(), card_matrix, card_values, eval_game_c, eval_game_p, flop_card_1, flop_card_2, flop_card_3, flop_cards_drawn, hole_card, hole_cards_drawn, privatebet_info::maxplayers, no_of_cards, no_of_flop_cards, no_of_hole_cards, no_of_river_card, no_of_turn_card, river_card, river_card_drawn, privatebet_vars::round, turn_card, and turn_card_drawn.
Referenced by bet_dcv_backend().
bet_relay()
int32_t bet_relay (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 584 of file host.c.
References privatebet_info::pubsock.
Referenced by bet_dcv_backend(), and bet_player_betting_statemachine().
bet_seats()
int32_t bet_seats (struct lws * wsi, cJSON * argjson)
Definition at line 110 of file host.c.
References initialize_seat(), max_players, and privatebet_info::pubsock.
Referenced by bet_dcv_frontend().
dcv_lws_write()
void dcv_lws_write (cJSON * data)
Definition at line 80 of file host.c.
References dcv_data_exists, dcv_data_to_write, and wsi_global_host.
Referenced by bet_push_dcv_to_gui(), and bet_push_joinInfo().