Bet: privatebet/cashier.c File Reference
cashier.c File Reference
#include "bet.h"
#include "client.h"
#include "cashier.h"
#include "network.h"
#include "common.h"
#include "commands.h"
#include "storage.h"
#include "misc.h"
Functions
void bet_game_multisigaddress ()
void bet_compute_m_of_n_msig_addr ()
void bet_check_cashier_nodes ()
void bet_check_cashiers_status ()
int32_t bet_send_status (struct cashier *cashier_info, char *id)
int32_t bet_process_lock_in_tx (cJSON *argjson, struct cashier *cashier_info)
int32_t bet_cashier_process_raw_msig_tx (cJSON *argjson, struct cashier *cashier_info)
int32_t bet_process_payout_tx (cJSON *argjson, struct cashier *cashier_info)
int32_t bet_process_game_info (cJSON *argjson, struct cashier *cashier_info)
cJSON * bet_resolve_game_dispute (cJSON *game_info)
int32_t bet_process_solve (cJSON *argjson, struct cashier *cashier_info)
int32_t bet_validate_game_details (cJSON *argjson, struct cashier *cashier_info)
void bet_cashier_status_loop (void *_ptr)
static int32_t bet_update_tx_spent (cJSON *argjson)
static cJSON * bet_reverse_disputed_tx (cJSON *game_info)
int32_t bet_process_dispute (cJSON *argjson, struct cashier *cashier_info)
static int32_t bet_process_dealer_info (cJSON *argjson)
static int32_t bet_check_dealer_status (char *dealer_ip)
static int32_t bet_process_rqst_dealer_info (cJSON *argjson, struct cashier *cashier_info)
static int32_t bet_process_find_bvv (cJSON *argjson, struct cashier *cashier_info)
static void bet_process_add_bvv (cJSON *argjson, struct cashier *cashier_info)
void bet_cashier_backend_thrd (void *_ptr)
void bet_cashier_server_loop (void *_ptr)
int32_t bet_submit_msig_raw_tx (cJSON *tx)
char * bet_send_message_to_notary (cJSON *argjson, char *notary_node_ip)
cJSON * bet_msg_cashier_with_response_id (cJSON *argjson, char *cashier_ip, char *method_name)
int32_t bet_msg_cashier (cJSON *argjson, char *cashier_ip)
int32_t * bet_msg_multiple_cashiers (cJSON *argjson, char **cashier_ips, int no_of_cashiers)
void bet_resolve_disputed_tx ()
void bet_raise_dispute (char *tx_id)
void bet_handle_game (int argc, char **argv)
void find_bvv ()
Variables
int32_t no_of_notaries
int32_t threshold_value = 2
char ** notary_node_ips = NULL
char ** notary_node_pubkeys = NULL
char dev_fund_addr [64] = { "RSdMRYeeouw3hepxNgUzHn34qFhn1tsubb" }
struct cashier * cashier_info = NULL
int32_t live_notaries = 0
int32_t * notary_status = NULL
int32_t notary_response = 0
double table_stack_in_chips = 0.01
double chips_tx_fee = 0.0005
char * legacy_m_of_n_msig_addr = NULL
int32_t bvv_state = 0
char dealer_ip_for_bvv [128]
Function Documentation
bet_cashier_backend_thrd()
void bet_cashier_backend_thrd (void * _ptr)
Definition at line 691 of file cashier.c.
References bet_cashier_process_raw_msig_tx(), bet_process_add_bvv(), bet_process_dealer_info(), bet_process_dispute(), bet_process_find_bvv(), bet_process_game_info(), bet_process_lock_in_tx(), bet_process_payout_tx(), bet_process_rqst_dealer_info(), bet_process_solve(), bet_send_status(), bet_update_tx_spent(), bet_validate_game_details(), cashier_info, chips_add_multisig_address_from_list(), and cashier::msg.
Referenced by bet_cashier_server_loop().
bet_cashier_process_raw_msig_tx()
int32_t bet_cashier_process_raw_msig_tx (cJSON * argjson, struct cashier * cashier_info)
Definition at line 180 of file cashier.c.
References cashier::c_pubsock, cashier_info, and chips_sign_raw_tx_with_wallet().
Referenced by bet_cashier_backend_thrd().
bet_cashier_server_loop()
void bet_cashier_server_loop (void * _ptr)
Definition at line 734 of file cashier.c.
References bet_cashier_backend_thrd(), cashier::c_pubsock, cashier::c_pullsock, cashier_info, and cashier::msg.
Referenced by bet_cashier_server_thrd().
bet_cashier_status_loop()
void bet_cashier_status_loop (void * _ptr)
Definition at line 393 of file cashier.c.
References cashier::c_pushsock, cashier::c_subsock, cashier_info, live_notaries, cashier::msg, and unique_id.
Referenced by bet_send_message_to_notary().
bet_check_cashier_nodes()
void bet_check_cashier_nodes ()
Definition at line 110 of file cashier.c.
References bet_check_cashiers_status(), live_notaries, no_of_notaries, notary_node_ips, and notary_status.
Referenced by playing_nodes_init().
bet_check_cashiers_status()
void bet_check_cashiers_status ()
Definition at line 128 of file cashier.c.
References bet_msg_cashier_with_response_id(), live_notaries, no_of_notaries, notary_node_ips, notary_status, and unique_id.
Referenced by bet_check_cashier_nodes(), bet_process_dispute(), bet_process_solve(), chips_spend_msig_tx(), and chips_spend_msig_txs().
bet_check_dealer_status()
static int32_t bet_check_dealer_status (char * dealer_ip) static
Definition at line 586 of file cashier.c.
References bet_msg_dealer_with_response_id(), bet_run_query(), dealer_ip, sql_query_size, and unique_id.
bet_compute_m_of_n_msig_addr()
void bet_compute_m_of_n_msig_addr ()
Definition at line 94 of file cashier.c.
References chips_add_multisig_address(), chips_import_address(), chips_iswatchonly(), and legacy_m_of_n_msig_addr.
Referenced by dealer_node_init().
bet_game_multisigaddress()
void bet_game_multisigaddress ()
Definition at line 71 of file cashier.c.
References bet_msg_cashier(), no_of_notaries, notary_node_ips, notary_node_pubkeys, notary_status, and threshold_value.
Referenced by dealer_node_init().
bet_handle_game()
void bet_handle_game (int argc, char ** argv)
Definition at line 955 of file cashier.c.
References bet_raise_dispute(), bet_resolve_disputed_tx(), bet_show_fail_history(), bet_show_success_history(), and sqlite3_get_game_details().
Referenced by main().
bet_msg_cashier()
int32_t bet_msg_cashier (cJSON * argjson, char * cashier_ip)
Definition at line 870 of file cashier.c.
References bet_nanosock(), bet_tcp_sock_address(), cashier::c_pushsock, and cashier_ip.
Referenced by bet_game_info(), bet_game_multisigaddress(), bet_msg_multiple_cashiers(), bet_player_handle_stack_info_resp(), bet_send_dealer_info_to_cashier(), chips_create_payout_tx(), and find_bvv().
bet_msg_cashier_with_response_id()
cJSON* bet_msg_cashier_with_response_id (cJSON * argjson, char * cashier_ip, char * method_name)
Definition at line 825 of file cashier.c.
References bet_nanosock(), bet_tcp_sock_address(), cashier::c_pushsock, cashier::c_subsock, cashier_ip, and unique_id.
Referenced by bet_check_cashiers_status(), bet_get_available_dealers(), bet_raise_dispute(), bet_resolve_game_dispute(), chips_sign_msig_tx(), chips_sign_msig_tx_of_table_id(), and find_bvv().
bet_msg_multiple_cashiers()
int32_t* bet_msg_multiple_cashiers (cJSON * argjson, char ** cashier_ips, int no_of_cashiers)
Definition at line 891 of file cashier.c.
References bet_msg_cashier().
Referenced by bet_resolve_game_dispute().
bet_process_add_bvv()
static void bet_process_add_bvv (cJSON * argjson, struct cashier * cashier_info) static
Definition at line 679 of file cashier.c.
References bet_bvv_thrd(), bvv_state, and dealer_ip_for_bvv.
Referenced by bet_cashier_backend_thrd().
bet_process_dealer_info()
static int32_t bet_process_dealer_info (cJSON * argjson) static
Definition at line 573 of file cashier.c.
References bet_run_query(), and sql_query_size.
Referenced by bet_cashier_backend_thrd().
bet_process_dispute()
int32_t bet_process_dispute (cJSON * argjson, struct cashier * cashier_info)
Definition at line 538 of file cashier.c.
References bet_check_cashiers_status(), bet_reverse_disputed_tx(), cashier::c_pubsock, cashier_info, chips_extract_data(), hexstr_to_str(), player_info, and tx_data_size.
Referenced by bet_cashier_backend_thrd().
bet_process_find_bvv()
static int32_t bet_process_find_bvv (cJSON * argjson, struct cashier * cashier_info) static
Definition at line 651 of file cashier.c.
References bet_bvv, bet_bvv_reset(), bet_msg_dealer_with_response_id(), bvv_state, bvv_vars, cashier::c_pubsock, cashier_info, dcv_state, dealer_ip_for_bvv, and unique_id.
Referenced by bet_cashier_backend_thrd().
bet_process_game_info()
int32_t bet_process_game_info (cJSON * argjson, struct cashier * cashier_info)
Definition at line 216 of file cashier.c.
References bet_run_query().
Referenced by bet_cashier_backend_thrd().
bet_process_lock_in_tx()
int32_t bet_process_lock_in_tx (cJSON * argjson, struct cashier * cashier_info)
Definition at line 164 of file cashier.c.
References bet_run_query(), cashier::c_pubsock, and cashier_info.
Referenced by bet_cashier_backend_thrd().
bet_process_payout_tx()
int32_t bet_process_payout_tx (cJSON * argjson, struct cashier * cashier_info)
Definition at line 199 of file cashier.c.
References bet_run_query().
Referenced by bet_cashier_backend_thrd().
bet_process_rqst_dealer_info()
static int32_t bet_process_rqst_dealer_info (cJSON * argjson, struct cashier * cashier_info) static
Definition at line 609 of file cashier.c.
References bet_msg_dealer_with_response_id(), cashier::c_pubsock, cashier_info, sqlite3_delete_dealer(), sqlite3_get_dealer_info_details(), and unique_id.
Referenced by bet_cashier_backend_thrd().
bet_process_solve()
int32_t bet_process_solve (cJSON * argjson, struct cashier * cashier_info)
Definition at line 359 of file cashier.c.
References bet_check_cashiers_status(), and bet_resolve_game_dispute().
Referenced by bet_cashier_backend_thrd().
bet_raise_dispute()
void bet_raise_dispute (char * tx_id)
Definition at line 921 of file cashier.c.
References bet_msg_cashier_with_response_id(), bet_run_query(), no_of_notaries, notary_node_ips, notary_status, sql_query_size, and unique_id.
Referenced by bet_handle_game(), and bet_resolve_disputed_tx().
bet_resolve_disputed_tx()
void bet_resolve_disputed_tx ()
Definition at line 902 of file cashier.c.
References bet_raise_dispute(), and sqlite3_get_game_details().
Referenced by bet_handle_game().
bet_resolve_game_dispute()
cJSON* bet_resolve_game_dispute (cJSON * game_info)
Definition at line 236 of file cashier.c.
References bet_msg_cashier_with_response_id(), bet_msg_multiple_cashiers(), bet_run_query(), chips_create_tx_from_tx_list(), chips_send_raw_tx(), chips_sign_msig_tx_of_table_id(), no_of_notaries, notary_node_ips, notary_status, sql_query_size, tx_ids, and unique_id.
Referenced by bet_process_solve().
bet_reverse_disputed_tx()
static cJSON* bet_reverse_disputed_tx (cJSON * game_info) static
Definition at line 442 of file cashier.c.
References chips_create_tx_from_tx_list(), chips_import_address(), chips_iswatchonly(), chips_send_raw_tx(), chips_sign_msig_tx(), no_of_notaries, notary_node_ips, notary_status, and tx_ids.
Referenced by bet_process_dispute().
bet_send_message_to_notary()
char* bet_send_message_to_notary (cJSON * argjson, char * notary_node_ip)
Definition at line 789 of file cashier.c.
References bet_cashier_status_loop(), bet_nanosock(), bet_tcp_sock_address(), cashier::c_pushsock, cashier::c_subsock, cashier_info, and cashier::msg.
bet_send_status()
int32_t bet_send_status (struct cashier * cashier_info, char * id)
Definition at line 146 of file cashier.c.
References cashier::c_pubsock, and cashier_info.
Referenced by bet_cashier_backend_thrd().
bet_submit_msig_raw_tx()
int32_t bet_submit_msig_raw_tx (cJSON * tx)
Definition at line 771 of file cashier.c.
References cashier::c_pushsock, and cashier_info.
bet_update_tx_spent()
static int32_t bet_update_tx_spent (cJSON * argjson) static
Definition at line 427 of file cashier.c.
References bet_run_query(), and sql_query_size.
Referenced by bet_cashier_backend_thrd().
bet_validate_game_details()
int32_t bet_validate_game_details (cJSON * argjson, struct cashier * cashier_info)
Definition at line 374 of file cashier.c.
References cashier::c_pubsock, and cashier_info.
Referenced by bet_cashier_backend_thrd().
find_bvv()
void find_bvv ()
Definition at line 985 of file cashier.c.
References bet_msg_cashier(), bet_msg_cashier_with_response_id(), bvv_info, dealer_ip, no_of_notaries, notary_node_ips, notary_status, and unique_id.
Referenced by bet_evaluate_hand(), and main().
Variable Documentation
bvv_state
int32_t bvv_state = 0
Definition at line 68 of file cashier.c.
Referenced by bet_bvv_backend_loop(), bet_process_add_bvv(), and bet_process_find_bvv().
cashier_info
struct cashier* cashier_info = NULL
Definition at line 49 of file cashier.c.
Referenced by bet_cashier_backend_thrd(), bet_cashier_client_initialize(), bet_cashier_deinitialize(), bet_cashier_process_raw_msig_tx(), bet_cashier_server_initialize(), bet_cashier_server_loop(), bet_cashier_server_thrd(), bet_cashier_status_loop(), bet_process_dispute(), bet_process_find_bvv(), bet_process_lock_in_tx(), bet_process_rqst_dealer_info(), bet_send_message_to_notary(), bet_send_status(), bet_submit_msig_raw_tx(), and bet_validate_game_details().
chips_tx_fee
double chips_tx_fee = 0.0005
Definition at line 64 of file cashier.c.
Referenced by bet_bvv_backend(), bet_dcv_bvv_join(), bet_dcv_poker_winner(), bet_dcv_stack_info_resp(), bet_parse_dealer_config_file(), bet_player_handle_stack_info_resp(), bet_player_wallet_info(), bet_player_withdraw_request(), chips_create_payout_tx(), chips_create_raw_tx(), chips_create_raw_tx_with_data(), chips_create_tx_from_tx_list(), and ln_establish_channel().
dealer_ip_for_bvv
char dealer_ip_for_bvv[128]
Definition at line 69 of file cashier.c.
Referenced by bet_process_add_bvv(), and bet_process_find_bvv().
dev_fund_addr
char dev_fund_addr[64] = { "RSdMRYeeouw3hepxNgUzHn34qFhn1tsubb" }
Definition at line 47 of file cashier.c.
Referenced by bet_dcv_poker_winner().
legacy_m_of_n_msig_addr
char* legacy_m_of_n_msig_addr = NULL
Definition at line 66 of file cashier.c.
Referenced by bet_compute_m_of_n_msig_addr(), bet_dcv_backend_thrd(), bet_dcv_poker_winner(), bet_dcv_stack_info_resp(), bet_player_handle_stack_info_resp(), chips_check_if_tx_unspent(), chips_check_tx_exists(), and chips_create_payout_tx().
live_notaries
int32_t live_notaries = 0
Definition at line 50 of file cashier.c.
Referenced by bet_cashier_status_loop(), bet_check_cashier_nodes(), bet_check_cashiers_status(), and chips_add_multisig_address().
no_of_notaries
int32_t no_of_notaries
Definition at line 10 of file cashier.c.
Referenced by bet_check_cashier_nodes(), bet_check_cashiers_status(), bet_dcv_process_tx(), bet_dcv_stack_info_resp(), bet_game_info(), bet_game_multisigaddress(), bet_get_available_dealers(), bet_parse_cashier_nodes_file(), bet_raise_dispute(), bet_resolve_game_dispute(), bet_reverse_disputed_tx(), bet_send_dealer_info_to_cashier(), chips_add_multisig_address(), chips_create_payout_tx(), chips_spend_msig_tx(), chips_spend_msig_txs(), find_bvv(), and payout_tx_data_info().
notary_node_ips
char** notary_node_ips = NULL
Definition at line 40 of file cashier.c.
Referenced by bet_check_cashier_nodes(), bet_check_cashiers_status(), bet_dcv_process_tx(), bet_dcv_stack_info_resp(), bet_game_info(), bet_game_multisigaddress(), bet_get_available_dealers(), bet_parse_cashier_nodes_file(), bet_raise_dispute(), bet_resolve_game_dispute(), bet_reverse_disputed_tx(), bet_send_dealer_info_to_cashier(), chips_create_payout_tx(), chips_spend_msig_tx(), chips_spend_msig_txs(), find_bvv(), and payout_tx_data_info().
notary_node_pubkeys
char** notary_node_pubkeys = NULL
Definition at line 41 of file cashier.c.
Referenced by bet_game_multisigaddress(), bet_parse_cashier_nodes_file(), and chips_add_multisig_address().
notary_response
int32_t notary_response = 0
Definition at line 52 of file cashier.c.
notary_status
int32_t* notary_status = NULL
Definition at line 51 of file cashier.c.
Referenced by bet_check_cashier_nodes(), bet_check_cashiers_status(), bet_dcv_process_tx(), bet_dcv_stack_info_resp(), bet_game_info(), bet_game_multisigaddress(), bet_get_available_dealers(), bet_parse_cashier_nodes_file(), bet_raise_dispute(), bet_resolve_game_dispute(), bet_reverse_disputed_tx(), bet_send_dealer_info_to_cashier(), chips_add_multisig_address(), chips_create_payout_tx(), chips_spend_msig_tx(), chips_spend_msig_txs(), find_bvv(), and payout_tx_data_info().
table_stack_in_chips
double table_stack_in_chips = 0.01
Definition at line 63 of file cashier.c.
Referenced by bet_bvv_backend(), bet_dcv_bvv_join(), bet_dcv_stack_info_resp(), bet_parse_dealer_config_file(), bet_player_handle_stack_info_resp(), and bet_player_wallet_info().
threshold_value
int32_t threshold_value = 2
Definition at line 18 of file cashier.c.
Referenced by bet_dcv_process_tx(), bet_dcv_stack_info_resp(), bet_game_multisigaddress(), bet_player_handle_stack_info_resp(), chips_add_multisig_address(), chips_add_multisig_address_from_list(), and payout_tx_data_info().