Bet: privatebet/bet.c File Reference
bet.c File Reference
#include "bet.h"
#include "../includes/curl/curl.h"
#include "../log/macrologger.h"
#include "cards777.h"
#include "cashier.h"
#include "client.h"
#include "commands.h"
#include "common.h"
#include "gfshare.h"
#include "host.h"
#include "network.h"
#include "table.h"
#include "storage.h"
#include "config.h"
#include "heartbeat.h"
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
Macros
#define LIVE_THREAD 1
Functions
static void bet_cashier_client_initialize (char *node_ip, const int32_t port)
static void bet_cashier_deinitialize ()
static void bet_player_initialize (char *dcv_ip, const int32_t port)
static void bet_player_deinitialize ()
static void bet_player_thrd (char *dcv_ip, const int32_t port)
static void bet_bvv_initialize (char *dcv_ip, const int32_t port)
static void bet_bvv_deinitialize ()
void bet_bvv_thrd (char *dcv_ip, const int32_t port)
static void bet_dcv_initialize (char *dcv_ip, const int32_t port)
static void bet_dcv_deinitialize ()
static void bet_dcv_thrd (char *dcv_ip, const int32_t port)
static void bet_cashier_server_initialize (char *node_ip, const int32_t port)
static void bet_cashier_server_thrd (char *node_ip, const int32_t port)
static void bet_display_usage ()
static void bet_set_unique_id ()
static void common_init ()
static void playing_nodes_init ()
static void dealer_node_init ()
static void bet_send_dealer_info_to_cashier (char *dealer_ip)
static char * bet_pick_dealer ()
int main (int argc, char **argv)
bits256 curve25519_fieldelement (bits256 hash)
bits256 card_rand256 (int32_t privkeyflag, int8_t index)
struct pair256 deckgen_common (struct pair256 *randcards, int32_t numcards)
void deckgen_common2 (struct pair256 *randcards, int32_t numcards)
struct pair256 deckgen_player (bits256 *playerprivs, bits256 *playercards, int32_t *permis, int32_t numcards)
int32_t sg777_deckgen_vendor (int32_t playerid, bits256 *cardprods, bits256 *finalcards, int32_t numcards, bits256 *playercards, bits256 deckid)
struct pair256 p2p_bvv_init (bits256 *keys, struct pair256 b_key, bits256 *blindings, bits256 *blindedcards, bits256 *finalcards, int32_t numcards, int32_t numplayers, int32_t playerid, bits256 deckid)
Variables
struct privatebet_info * bet_player = NULL
struct privatebet_vars * player_vars = NULL
uint8_t sharenrs [256]
bits256 deckid
bits256 playershares [CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
int32_t permis_d [CARDS777_MAXCARDS]
int32_t permis_b [CARDS777_MAXCARDS]
bits256 v_hash [CARDS777_MAXCARDS][CARDS777_MAXCARDS]
bits256 g_hash [CARDS777_MAXPLAYERS][CARDS777_MAXCARDS]
struct enc_share * g_shares = NULL
char dealer_ip [20]
char cashier_ip [20]
char unique_id [65]
struct seat_info player_seats_info [CARDS777_MAXPLAYERS]
int32_t player_pos [CARDS777_MAXPLAYERS]
int32_t max_players = 2
static const int32_t poker_deck_size = 52
Macro Definition Documentation
LIVE_THREAD
#define LIVE_THREAD 1
Definition at line 38 of file bet.c.
Function Documentation
bet_bvv_deinitialize()
static void bet_bvv_deinitialize () static
Definition at line 195 of file bet.c.
References bet_bvv, and bvv_vars.
Referenced by bet_bvv_thrd().
bet_bvv_initialize()
static void bet_bvv_initialize (char * dcv_ip, const int32_t port) static
Definition at line 172 of file bet.c.
References bet_bvv, bet_info_set(), bet_nanosock(), bet_tcp_sock_address(), bvv_vars, CARDS777_CHIPSIZE, CARDS777_MAXCHIPS, CARDS777_MAXPLAYERS, privatebet_info::chipsize, max_players, privatebet_info::maxchips, privatebet_info::maxplayers, privatebet_info::myplayerid, privatebet_info::numplayers, poker_deck_size, privatebet_info::pushsock, and privatebet_info::subsock.
Referenced by bet_bvv_thrd().
bet_bvv_thrd()
void bet_bvv_thrd (char * dcv_ip, const int32_t port)
Definition at line 203 of file bet.c.
References bet_bvv, bet_bvv_backend_loop(), bet_bvv_deinitialize(), and bet_bvv_initialize().
Referenced by bet_process_add_bvv().
bet_cashier_client_initialize()
static void bet_cashier_client_initialize (char * node_ip, const int32_t port) static
Definition at line 69 of file bet.c.
References bet_nanosock(), bet_tcp_sock_address(), cashier::c_pushsock, cashier::c_subsock, and cashier_info.
bet_cashier_deinitialize()
static void bet_cashier_deinitialize () static
Definition at line 86 of file bet.c.
References cashier_info.
Referenced by bet_cashier_server_thrd().
bet_cashier_server_initialize()
static void bet_cashier_server_initialize (char * node_ip, const int32_t port) static
Definition at line 308 of file bet.c.
References bet_nanosock(), bet_tcp_sock_address(), cashier::c_pubsock, cashier::c_pullsock, and cashier_info.
Referenced by bet_cashier_server_thrd().
bet_cashier_server_thrd()
static void bet_cashier_server_thrd (char * node_ip, const int32_t port) static
Definition at line 325 of file bet.c.
References bet_cashier_deinitialize(), bet_cashier_server_initialize(), bet_cashier_server_loop(), and cashier_info.
Referenced by main().
bet_dcv_deinitialize()
static void bet_dcv_deinitialize () static
Definition at line 263 of file bet.c.
References bet_dcv, and dcv_vars.
Referenced by bet_dcv_thrd().
bet_dcv_initialize()
static void bet_dcv_initialize (char * dcv_ip, const int32_t port) static
Definition at line 218 of file bet.c.
References privatebet_vars::bet_actions, bet_dcv, bet_info_set(), bet_nanosock(), bet_tcp_sock_address(), privatebet_vars::betamount, privatebet_info::cardid, CARDS777_CHIPSIZE, CARDS777_MAXCHIPS, CARDS777_MAXPLAYERS, CARDS777_MAXROUNDS, privatebet_info::chipsize, dcv_vars, privatebet_vars::funds, privatebet_vars::last_raise, privatebet_vars::last_turn, max_players, privatebet_info::maxchips, privatebet_info::maxplayers, privatebet_info::msg, privatebet_info::myplayerid, privatebet_info::no_of_turns, privatebet_info::numplayers, player_pos, poker_deck_size, privatebet_vars::pot, privatebet_info::pubsock, privatebet_info::pullsock, privatebet_vars::round, privatebet_info::turni, and privatebet_vars::turni.
Referenced by bet_dcv_thrd().
bet_dcv_thrd()
static void bet_dcv_thrd (char * dcv_ip, const int32_t port) static
Definition at line 271 of file bet.c.
References bet_dcv, bet_dcv_backend_loop(), bet_dcv_deinitialize(), bet_dcv_frontend_loop(), bet_dcv_heartbeat_loop(), and bet_dcv_initialize().
Referenced by main().
bet_display_usage()
static void bet_display_usage () static
Definition at line 340 of file bet.c.
Referenced by main().
bet_pick_dealer()
static char* bet_pick_dealer () static
Definition at line 395 of file bet.c.
References bet_get_available_dealers(), bet_msg_dealer_with_response_id(), and unique_id.
Referenced by main().
bet_player_deinitialize()
static void bet_player_deinitialize () static
Definition at line 115 of file bet.c.
References bet_player, and player_vars.
Referenced by bet_player_thrd().
bet_player_initialize()
static void bet_player_initialize (char * dcv_ip, const int32_t port) static
Definition at line 92 of file bet.c.
References bet_info_set(), bet_nanosock(), bet_player, bet_tcp_sock_address(), CARDS777_CHIPSIZE, CARDS777_MAXCHIPS, CARDS777_MAXPLAYERS, privatebet_info::chipsize, max_players, privatebet_info::maxchips, privatebet_info::maxplayers, privatebet_info::numplayers, player_vars, poker_deck_size, privatebet_info::pushsock, and privatebet_info::subsock.
Referenced by bet_player_thrd().
bet_player_thrd()
static void bet_player_thrd (char * dcv_ip, const int32_t port) static
Definition at line 123 of file bet.c.
References bet_player, bet_player_backend_loop(), bet_player_deinitialize(), bet_player_frontend_loop(), bet_player_frontend_read_loop(), bet_player_frontend_write_loop(), and bet_player_initialize().
Referenced by main().
bet_send_dealer_info_to_cashier()
static void bet_send_dealer_info_to_cashier (char * dealer_ip) static
Definition at line 380 of file bet.c.
References bet_msg_cashier(), dealer_ip, no_of_notaries, notary_node_ips, and notary_status.
Referenced by main().
bet_set_unique_id()
static void bet_set_unique_id () static
Definition at line 348 of file bet.c.
References unique_id.
Referenced by main().
card_rand256()
bits256 card_rand256 (int32_t privkeyflag, int8_t index)
Definition at line 475 of file bet.c.
common_init()
static void common_init () static
Definition at line 356 of file bet.c.
References bet_parse_cashier_nodes_file(), bet_sqlite3_init(), check_ln_chips_sync(), and libgfshare_init().
Referenced by main(), and playing_nodes_init().
curve25519_fieldelement()
bits256 curve25519_fieldelement (bits256 hash)
Definition at line 469 of file bet.c.
Referenced by bet_decode_card(), and p2p_bvv_init().
dealer_node_init()
static void dealer_node_init () static
Definition at line 371 of file bet.c.
References bet_compute_m_of_n_msig_addr(), bet_game_multisigaddress(), bet_init_player_seats_info(), bet_parse_dealer_config_file(), and bet_set_table_id().
Referenced by main().
deckgen_common()
struct pair256 deckgen_common (struct pair256 * randcards, int32_t numcards)
Definition at line 475 of file bet.c.
deckgen_common2()
void deckgen_common2 (struct pair256 * randcards, int32_t numcards)
Definition at line 498 of file bet.c.
References pair256::priv, and pair256::prod.
Referenced by p2p_bvv_init().
deckgen_player()
struct pair256 deckgen_player (bits256 * playerprivs, bits256 * playercards, int32_t * permis, int32_t numcards)
Definition at line 498 of file bet.c.
Referenced by bet_client_join().
main()
int main (int argc, char ** argv)
Definition at line 416 of file bet.c.
References bet_cashier_server_thrd(), bet_dcv_thrd(), bet_display_usage(), bet_git_version(), bet_handle_game(), bet_parse_dealer_config_file(), bet_pick_dealer(), bet_player_thrd(), bet_send_dealer_info_to_cashier(), bet_set_unique_id(), cashier_ip, chips_transfer_funds(), common_init(), dealer_ip, dealer_node_init(), find_bvv(), and playing_nodes_init().
p2p_bvv_init()
struct pair256 p2p_bvv_init (bits256 * keys, struct pair256 b_key, bits256 * blindings, bits256 * blindedcards, bits256 * finalcards, int32_t numcards, int32_t numplayers, int32_t playerid, bits256 deckid)
Definition at line 524 of file bet.c.
References CARDS777_MAXCARDS, curve25519_fieldelement(), deckgen_common2(), deckid, fmul_donna(), g_hash, permis_d, pair256::priv, pair256::prod, and xoverz_donna().
Referenced by bet_bvv_init().
playing_nodes_init()
static void playing_nodes_init () static
Definition at line 365 of file bet.c.
References bet_check_cashier_nodes(), and common_init().
Referenced by main().
sg777_deckgen_vendor()
int32_t sg777_deckgen_vendor (int32_t playerid, bits256 * cardprods, bits256 * finalcards, int32_t numcards, bits256 * playercards, bits256 deckid)
Definition at line 524 of file bet.c.
Referenced by bet_dcv_init().
Variable Documentation
bet_player
struct privatebet_info* bet_player = NULL
Definition at line 40 of file bet.c.
Referenced by bet_client_join_res(), bet_player_deinitialize(), bet_player_frontend(), bet_player_initialize(), bet_player_process_player_join(), bet_player_thrd(), lws_callback_http_player(), and lws_callback_http_player_write().
cashier_ip
char cashier_ip[20]
Definition at line 52 of file bet.c.
Referenced by bet_msg_cashier(), bet_msg_cashier_with_response_id(), and main().
dealer_ip
char dealer_ip[20]
Definition at line 51 of file bet.c.
Referenced by bet_check_dealer_status(), bet_msg_dealer_with_response_id(), bet_send_dealer_info_to_cashier(), find_bvv(), main(), and sqlite3_delete_dealer().
deckid
bits256 deckid
Definition at line 44 of file bet.c.
Referenced by bet_player_create_invoice(), and p2p_bvv_init().
g_hash
bits256 g_hash[CARDS777_MAXPLAYERS][CARDS777_MAXCARDS]
Definition at line 48 of file bet.c.
Referenced by bet_client_dcv_init(), bet_dcv_deck_init_info(), bet_decode_card(), and p2p_bvv_init().
g_shares
struct enc_share* g_shares = NULL
Definition at line 49 of file bet.c.
Referenced by bet_bvv_init(), bet_bvv_reset(), bet_client_bvv_init(), bet_client_give_share(), and bet_get_own_share().
max_players
int32_t max_players = 2
Definition at line 65 of file bet.c.
Referenced by bet_bvv_backend(), bet_bvv_initialize(), bet_dcv_bvv_join(), bet_dcv_initialize(), bet_dcv_stack_info_resp(), bet_game(), bet_get_seats_json(), bet_init_player_seats_info(), bet_parse_dealer_config_file(), bet_player_handle_stack_info_resp(), bet_player_initialize(), bet_player_wallet_info(), and bet_seats().
permis_b
int32_t permis_b[CARDS777_MAXCARDS]
Definition at line 46 of file bet.c.
Referenced by bet_bvv_backend_loop(), and bet_bvv_reset().
permis_d
int32_t permis_d[CARDS777_MAXCARDS]
Definition at line 46 of file bet.c.
Referenced by bet_dcv_backend_loop(), bet_reset_all_dcv_params(), and p2p_bvv_init().
player_pos
int32_t player_pos[CARDS777_MAXPLAYERS]
Definition at line 57 of file bet.c.
Referenced by bet_dcv_initialize().
player_seats_info
struct seat_info player_seats_info[CARDS777_MAXPLAYERS]
Definition at line 53 of file bet.c.
Referenced by bet_dcv_check_pos_status(), bet_get_seats_json(), bet_init_player_seats_info(), and bet_player_join_req().
player_vars
struct privatebet_vars* player_vars = NULL
Definition at line 41 of file bet.c.
Referenced by bet_player_backend_loop(), bet_player_deinitialize(), bet_player_frontend(), and bet_player_initialize().
playershares
bits256 playershares[CARDS777_MAXCARDS][CARDS777_MAXPLAYERS]
Definition at line 45 of file bet.c.
Referenced by bet_client_receive_share(), bet_decode_card(), and bet_get_own_share().
poker_deck_size
const int32_t poker_deck_size = 52 static
Definition at line 67 of file bet.c.
Referenced by bet_bvv_initialize(), bet_dcv_initialize(), and bet_player_initialize().
sharenrs
uint8_t sharenrs[256]
Definition at line 43 of file bet.c.
Referenced by _gfshare_init_core(), bet_decode_card(), gfshare_calc_sharenrs(), gfshare_calc_shares(), gfshare_dec_newshares(), gfshare_init_sharenrs(), gfshare_initdec(), gfshare_initenc(), gfshare_recoverdata(), and gfshare_sg777_initdec().
unique_id
char unique_id[65]
Definition at line 53 of file bet.c.
Referenced by bet_cashier_status_loop(), bet_check_cashiers_status(), bet_check_dealer_status(), bet_get_available_dealers(), bet_msg_cashier_with_response_id(), bet_msg_dealer_with_response_id(), bet_pick_dealer(), bet_process_find_bvv(), bet_process_rqst_dealer_info(), bet_raise_dispute(), bet_resolve_game_dispute(), bet_set_unique_id(), chips_sign_msig_tx(), chips_sign_msig_tx_of_table_id(), and find_bvv().
v_hash
bits256 v_hash[CARDS777_MAXCARDS][CARDS777_MAXCARDS]
Definition at line 47 of file bet.c.
Referenced by bet_client_bvv_init(), and bet_decode_card().