Bet: /root/bet/privatebet/client.h File Reference
client.h File Reference
#include "bet.h"
Functions
char * enc_share_str (char hexstr[177], struct enc_share x)
struct enc_share get_API_enc_share (cJSON *obj)
int32_t bet_bvv_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_bvv_backend (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_bvv_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
bits256 bet_decode_card (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars, int32_t cardid)
int32_t bet_client_receive_share (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_give_share (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_get_own_share (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_turn (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_bvv_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_dcv_init (cJSON *dcv_info, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_join_res (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_client_join (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_player_backend_loop (void *_ptr)
int32_t ln_get_channel_status (char *id)
int32_t bet_player_ready (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_table_info (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void display_cards (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_player_frontend_loop ()
int32_t bet_player_backend (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_frontend (struct lws *wsi, cJSON *argjson)
void bet_bvv_backend_loop (void *_ptr)
int32_t bet_bvv_frontend (struct lws *wsi, cJSON *argjson)
void bet_bvv_frontend_loop (void *_ptr)
bits256 bet_get_deckid (int32_t playerID)
void bet_push_client (cJSON *argjson)
void make_command (int argc, char **argv, cJSON **argjson)
int32_t ln_listfunds ()
int32_t ln_get_uri (char **uri)
int32_t ln_connect_uri (char *uri)
int32_t ln_fundChannel (char *channel_id)
int32_t ln_pay (char *bolt11)
void ln_connect (char *id)
void ln_check_peer_and_connect (char *id)
void rest_push_cards (struct lws *wsi, cJSON *argjson, int32_t this_playerID)
int32_t ln_pay_invoice (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
void player_lws_write (cJSON *data)
void rest_display_cards (cJSON *argjson, int32_t this_playerID)
Function Documentation
bet_bvv_backend()
int32_t bet_bvv_backend (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 539 of file client.c.
References bet_bvv_init(), bet_bvv_join_init(), bet_bvv_reset(), bet_check_bvv_ready(), bet_live_response(), and bet_table_info().
Referenced by bet_bvv_backend_loop().
bet_bvv_backend_loop()
void bet_bvv_backend_loop (void * _ptr)
Definition at line 472 of file client.c.
References bet_bvv_backend(), bet_permutation(), bvv_info, deck_bvv_info::permis, permis_b, privatebet_info::pushsock, privatebet_info::range, and privatebet_info::subsock.
Referenced by main().
bet_bvv_frontend()
int32_t bet_bvv_frontend (struct lws * wsi, cJSON * argjson)
Definition at line 446 of file client.c.
References bet_bvv_init(), bet_bvv_join_init(), bet_bvv_reset(), bet_check_bvv_ready(), bet_player_dealer_info(), and bet_table_info().
Referenced by lws_callback_http_bvv().
bet_bvv_frontend_loop()
void bet_bvv_frontend_loop (void * _ptr)
Definition at line 1825 of file client.c.
References interrupted_bvv, mount_bvv, and protocols_bvv.
Referenced by main().
bet_bvv_init()
int32_t bet_bvv_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 183 of file client.c.
References bvv_info, deck_bvv_info::bvv_key, enc_share::bytes, CARDS777_MAXCARDS, CARDS777_MAXPLAYERS, deck_bvv_info::deckid, enc_share_str(), g_shares, privatebet_info::maxplayers, deck_bvv_info::maxplayers, privatebet_info::numplayers, deck_bvv_info::numplayers, p2p_bvv_init(), pair256::priv, pair256::prod, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_bvv_backend(), and bet_bvv_frontend().
bet_bvv_reset()
void bet_bvv_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 436 of file client.c.
References bet_permutation(), bvv_info, g_shares, deck_bvv_info::permis, permis_b, and privatebet_info::range.
Referenced by bet_bvv_backend(), and bet_bvv_frontend().
bet_client_bvv_init()
int32_t bet_client_bvv_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1136 of file client.c.
References bet_player_ready(), deck_player_info::bvvblindcards, deck_player_info::bvvpubkey, enc_share::bytes, deck_player_info::cardprods, CARDS777_MAXCARDS, CARDS777_MAXPLAYERS, g_shares, get_API_enc_share(), privatebet_info::myplayerid, privatebet_info::numplayers, player_info, deck_player_info::player_key, pair256::priv, privatebet_info::range, v_hash, and xoverz_donna().
Referenced by bet_player_backend().
bet_client_dcv_init()
int32_t bet_client_dcv_init (cJSON * dcv_info, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1185 of file client.c.
References deck_player_info::cardprods, deck_player_info::deckid, g_hash, privatebet_info::numplayers, player_info, and privatebet_info::range.
Referenced by bet_player_backend().
bet_client_give_share()
int32_t bet_client_give_share (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1007 of file client.c.
References bet_decrypt(), deck_player_info::bvvpubkey, enc_share::bytes, g_shares, privatebet_info::myplayerid, privatebet_info::numplayers, player_info, deck_player_info::player_key, pair256::priv, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_player_backend().
bet_client_init()
int32_t bet_client_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1213 of file client.c.
References enc_share::bytes, deck_player_info::cardpubkeys, privatebet_info::myplayerid, player_info, deck_player_info::player_key, pair256::prod, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_player_backend().
bet_client_join()
int32_t bet_client_join (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1526 of file client.c.
References enc_share::bytes, deck_player_info::cardprivkeys, deck_player_info::cardpubkeys, deckgen_player(), make_command(), deck_player_info::permis, player_info, deck_player_info::player_key, pair256::prod, privatebet_info::pushsock, and privatebet_info::range.
Referenced by bet_player_backend(), and bet_player_frontend().
bet_client_join_res()
int32_t bet_client_join_res (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1384 of file client.c.
References bet_check_player_stack(), bet_player, enc_share::bytes, channel_fund_satoshis, ln_check_peer_and_connect(), ln_get_channel_status(), make_command(), privatebet_info::myplayerid, privatebet_vars::player_funds, player_info, deck_player_info::player_key, player_lws_write(), pair256::prod, and privatebet_info::pushsock.
Referenced by bet_player_backend().
bet_client_receive_share()
int32_t bet_client_receive_share (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 918 of file client.c.
References bet_decode_card(), privatebet_info::maxplayers, privatebet_info::myplayerid, no_of_shares, number_cards_drawn, deck_player_info::permis, player_card_values, player_info, playershares, privatebet_info::pushsock, privatebet_info::range, and sharesflag.
Referenced by bet_player_backend().
bet_client_turn()
int32_t bet_client_turn (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1088 of file client.c.
References bet_get_own_share(), bet_player_ask_share(), privatebet_info::myplayerid, no_of_shares, privatebet_info::numplayers, and sharesflag.
Referenced by bet_player_backend().
bet_decode_card()
bits256 bet_decode_card (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars, int32_t cardid)
Definition at line 571 of file client.c.
References deck_player_info::bvvblindcards, deck_player_info::cardprivkeys, deck_player_info::cardprods, crecip_donna(), curve25519_fieldelement(), deck_player_info::deckid, fmul_donna(), g_hash, gfshare_calc_sharenrs(), gfshare_recoverdata(), privatebet_info::maxplayers, privatebet_info::myplayerid, no_of_player_cards, player_cards, player_info, deck_player_info::player_key, playershares, pair256::priv, privatebet_info::range, sharenrs, v_hash, and xoverz_donna().
Referenced by bet_client_receive_share().
bet_get_deckid()
bits256 bet_get_deckid (int32_t playerID)
Definition at line 2094 of file client.c.
References all_players_info, and deck_player_info::deckid.
bet_get_own_share()
int32_t bet_get_own_share (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1058 of file client.c.
References bet_decrypt(), deck_player_info::bvvpubkey, enc_share::bytes, g_shares, privatebet_info::myplayerid, privatebet_info::numplayers, player_info, deck_player_info::player_key, playershares, pair256::priv, privatebet_info::range, and sharesflag.
Referenced by bet_client_turn().
bet_player_backend()
int32_t bet_player_backend (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1874 of file client.c.
References bet_client_bvv_init(), bet_client_dcv_init(), bet_client_give_share(), bet_client_init(), bet_client_join(), bet_client_join_res(), bet_client_receive_share(), bet_client_turn(), bet_display_current_state(), bet_live_response(), bet_player_bet_round(), bet_player_betting_invoice(), bet_player_betting_statemachine(), bet_player_blinds_info(), bet_player_create_invoice(), bet_player_dealer_info(), bet_player_reset(), bet_player_winner(), bet_push_join_info(), bet_table_info(), chips_sign_raw_tx_with_wallet(), deck_player_info::deckid, privatebet_vars::funds, ln_listfunds(), ln_pay_invoice(), privatebet_info::myplayerid, player_info, player_lws_write(), and privatebet_info::pushsock.
Referenced by bet_player_backend_loop().
bet_player_backend_loop()
void bet_player_backend_loop (void * _ptr)
Definition at line 1975 of file client.c.
References bet_player_backend(), player_vars, privatebet_info::pushsock, and privatebet_info::subsock.
Referenced by main().
bet_player_frontend()
int32_t bet_player_frontend (struct lws * wsi, cJSON * argjson)
Definition at line 1646 of file client.c.
References bet_client_join(), bet_player, bet_player_reset(), bet_player_round_betting(), player_joined, and player_vars.
Referenced by lws_callback_http_player().
bet_player_frontend_loop()
void bet_player_frontend_loop ()
bet_player_ready()
int32_t bet_player_ready (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1117 of file client.c.
References enc_share::bytes, privatebet_info::myplayerid, and privatebet_info::pushsock.
Referenced by bet_client_bvv_init().
bet_player_reset()
int32_t bet_player_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1612 of file client.c.
References privatebet_vars::bet_actions, privatebet_vars::betamount, CARDS777_MAXROUNDS, hand_size, privatebet_info::maxplayers, no_of_player_cards, no_of_shares, number_cards_drawn, privatebet_info::numplayers, player_card_matrix, player_card_values, player_joined, player_lws_write(), privatebet_vars::pot, privatebet_info::range, and sharesflag.
Referenced by bet_player_backend(), and bet_player_frontend().
bet_push_client()
void bet_push_client (cJSON * argjson)
Definition at line 1851 of file client.c.
References player_lws_write().
Referenced by bet_player_dealer_info(), and bet_player_round_betting_response().
bet_table_info()
void bet_table_info (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1606 of file client.c.
Referenced by bet_bvv_backend(), bet_bvv_frontend(), and bet_player_backend().
display_cards()
void display_cards (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 873 of file client.c.
References hand_size, no_of_hole_cards, number_cards_drawn, player_card_values, and player_lws_write().
Referenced by bet_player_betting_statemachine().
enc_share_str()
char* enc_share_str (char hexstr[177], struct enc_share x)
Definition at line 158 of file client.c.
References enc_share::bytes.
Referenced by bet_bvv_init().
get_API_enc_share()
struct enc_share get_API_enc_share (cJSON * obj)
Definition at line 164 of file client.c.
References enc_share::bytes.
Referenced by bet_client_bvv_init().
ln_check_peer_and_connect()
void ln_check_peer_and_connect (char * id)
Definition at line 1263 of file client.c.
References ln_connect(), and make_command().
Referenced by bet_client_join_res().
ln_connect()
void ln_connect (char * id)
Definition at line 1244 of file client.c.
References make_command().
Referenced by ln_check_peer_and_connect().
ln_connect_uri()
int32_t ln_connect_uri (char * uri)
Definition at line 2156 of file client.c.
References ln_get_channel_status(), and make_command().
ln_fundChannel()
int32_t ln_fundChannel (char * channel_id)
Definition at line 2099 of file client.c.
References ln_get_channel_status(), and make_command().
ln_get_channel_status()
int32_t ln_get_channel_status (char * id)
Definition at line 1302 of file client.c.
References make_command().
Referenced by bet_award_winner(), bet_check_bvv_ready(), bet_client_join_res(), bet_dcv_bvv_join(), bet_ln_check(), ln_connect_uri(), and ln_fundChannel().
ln_get_uri()
int32_t ln_get_uri (char ** uri)
Definition at line 2053 of file client.c.
References make_command().
ln_listfunds()
int32_t ln_listfunds ()
Definition at line 2008 of file client.c.
References make_command().
Referenced by bet_player_backend().
ln_pay()
int32_t ln_pay (char * bolt11)
Definition at line 2312 of file client.c.
References make_command().
ln_pay_invoice()
int32_t ln_pay_invoice (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 677 of file client.c.
References make_command(), and privatebet_info::myplayerid.
Referenced by bet_player_backend(), and bet_player_paymentloop().
make_command()
void make_command (int argc, char ** argv, cJSON ** argjson)
Definition at line 102 of file client.c.
Referenced by bet_award_winner(), bet_bvv_connect(), bet_bvv_join_init(), bet_client_join(), bet_client_join_res(), bet_create_betting_invoice(), bet_create_invoice(), bet_dcv_bvv_join(), bet_dcv_pay(), bet_find_channel_balance(), bet_ln_check(), bet_player_betting_invoice(), bet_player_create_invoice(), bet_player_fundchannel(), bet_player_join_req(), bet_player_winner(), chips_create_raw_multi_sig_tx(), chips_create_raw_tx(), chips_get_balance(), chips_get_block_count(), chips_get_new_address(), chips_import_address(), chips_iswatchonly(), chips_list_address_groupings(), chips_list_unspent(), chips_lock_transaction(), chips_send_raw_tx(), chips_sign_raw_tx_with_wallet(), chips_validate_address(), ln_check_peer_and_connect(), ln_connect(), ln_connect_uri(), ln_dev_block_height(), ln_fundChannel(), ln_get_channel_status(), ln_get_uri(), ln_listfunds(), ln_pay(), and ln_pay_invoice().
player_lws_write()
void player_lws_write (cJSON * data)
Definition at line 86 of file client.c.
References data_exists, player_gui_data, ws_connection_status, and wsi_global_client.
Referenced by bet_client_join_res(), bet_player_backend(), bet_player_betting_statemachine(), bet_player_big_blind(), bet_player_blinds_info(), bet_player_reset(), bet_player_small_blind(), bet_push_client(), bet_push_join_info(), and display_cards().
rest_display_cards()
void rest_display_cards (cJSON * argjson, int32_t this_playerID)
Definition at line 2247 of file client.c.
References action_str, all_number_cards_drawn, all_player_card_values, big_blind_amount, face, hand_size, privatebet_info::maxplayers, NFACES, no_of_hole_cards, NSUITS, small_blind_amount, and suit.
rest_push_cards()
void rest_push_cards (struct lws * wsi, cJSON * argjson, int32_t this_playerID)
Definition at line 2200 of file client.c.
References all_number_cards_drawn, all_player_card_values, hand_size, and no_of_hole_cards.