Bet: privatebet/storage.h File Reference
storage.h File Reference
#include "bet.h"
#include <sqlite3.h>
Macros
#define sql_query_size 1024
Functions
void sqlite3_init_db_name ()
int32_t sqlite3_check_if_table_id_exists (const char *table_id)
int32_t sqlite3_check_if_table_exists (sqlite3 *db, const char *table_name)
sqlite3 * bet_get_db_instance ()
void bet_make_insert_query (int argc, char **argv, char **sql_query)
int32_t bet_run_query (char *sql_query)
void bet_create_schema ()
void bet_sqlite3_init ()
int32_t sqlite3_delete_dealer (char *dealer_ip)
cJSON * sqlite3_get_dealer_info_details ()
cJSON * sqlite3_get_game_details (int32_t opt)
cJSON * bet_show_fail_history ()
cJSON * bet_show_success_history ()
Macro Definition Documentation
sql_query_size
#define sql_query_size 1024
Definition at line 4 of file storage.h.
Function Documentation
bet_create_schema()
void bet_create_schema ()
Definition at line 145 of file storage.c.
References bet_get_db_instance(), no_of_tables, schemas, sqlite3_check_if_table_exists(), and table_names.
Referenced by bet_sqlite3_init().
bet_get_db_instance()
sqlite3* bet_get_db_instance ()
Definition at line 98 of file storage.c.
References db_name.
Referenced by bet_create_schema(), bet_run_query(), bet_show_fail_history(), bet_show_success_history(), sqlite3_check_if_table_exists(), sqlite3_check_if_table_id_exists(), sqlite3_get_dealer_info_details(), and sqlite3_get_game_details().
bet_make_insert_query()
void bet_make_insert_query (int argc, char ** argv, char ** sql_query)
Definition at line 111 of file storage.c.
Referenced by bet_game_info(), and bet_player_process_game_info().
bet_run_query()
int32_t bet_run_query (char * sql_query)
Definition at line 123 of file storage.c.
References bet_get_db_instance().
Referenced by bet_check_dealer_status(), bet_dcv_process_tx(), bet_game_info(), bet_player_handle_stack_info_resp(), bet_player_process_game_info(), bet_player_process_payout_tx(), bet_process_dealer_info(), bet_process_game_info(), bet_process_lock_in_tx(), bet_process_payout_tx(), bet_raise_dispute(), bet_resolve_game_dispute(), bet_update_tx_spent(), chips_create_payout_tx(), and sqlite3_delete_dealer().
bet_show_fail_history()
cJSON* bet_show_fail_history ()
Definition at line 274 of file storage.c.
References bet_get_db_instance(), chips_extract_data(), hexstr_to_str(), sql_query_size, and tx_data_size.
Referenced by bet_handle_game().
bet_show_success_history()
cJSON* bet_show_success_history ()
Definition at line 322 of file storage.c.
References bet_get_db_instance(), chips_extract_data(), hexstr_to_str(), sql_query_size, and tx_data_size.
Referenced by bet_handle_game().
bet_sqlite3_init()
void bet_sqlite3_init ()
Definition at line 170 of file storage.c.
References bet_create_schema(), and sqlite3_init_db_name().
Referenced by common_init().
sqlite3_check_if_table_exists()
int32_t sqlite3_check_if_table_exists (sqlite3 * db, const char * table_name)
Definition at line 69 of file storage.c.
References bet_get_db_instance(), and sql_query_size.
Referenced by bet_create_schema().
sqlite3_check_if_table_id_exists()
int32_t sqlite3_check_if_table_id_exists (const char * table_id)
Definition at line 39 of file storage.c.
References bet_get_db_instance(), and table_id.
sqlite3_delete_dealer()
int32_t sqlite3_delete_dealer (char * dealer_ip)
Definition at line 177 of file storage.c.
References bet_run_query(), dealer_ip, and sql_query_size.
Referenced by bet_process_rqst_dealer_info().
sqlite3_get_dealer_info_details()
cJSON* sqlite3_get_dealer_info_details ()
Definition at line 190 of file storage.c.
References bet_get_db_instance(), and sql_query_size.
Referenced by bet_process_rqst_dealer_info().
sqlite3_get_game_details()
cJSON* sqlite3_get_game_details (int32_t opt)
Definition at line 217 of file storage.c.
References bet_get_db_instance(), chips_get_wallet_address(), and sql_query_size.
Referenced by bet_handle_game(), and bet_resolve_disputed_tx().
sqlite3_init_db_name()
void sqlite3_init_db_name ()
Definition at line 30 of file storage.c.
References db_name.
Referenced by bet_sqlite3_init().