void bet_compute_m_of_n_msig_addr();
void bet_check_cashier_nodes();
int32_t bet_check_if_notary_is_active(char *notary_node_ip);
char *bet_check_all_cashier_nodes_status();
int32_t bet_send_status(struct cashier *cashier_info);
int32_t bet_process_lock_in_tx(cJSON *argjson, struct cashier *cashier_info);
int32_t bet_cashier_process_raw_msig_tx(cJSON *argjson, struct cashier *cashier_info);
int32_t bet_process_payout_tx(cJSON *argjson, struct cashier *cashier_info);
int32_t bet_process_game_info(cJSON *argjson, struct cashier *cashier_info);
int32_t bet_cashier_backend(cJSON *argjson, struct cashier *cashier_info);
void bet_cashier_server_loop(void *_ptr);
void bet_cashier_client_loop(void *_ptr);
void bet_cashier_status_loop(void *_ptr);
int32_t bet_submit_msig_raw_tx(cJSON *tx);
char *bet_send_message_to_notary(cJSON *argjson, char *notary_node_ip);
cJSON *bet_send_single_message_to_notary(cJSON *argjson, char *notary_node_ip);
cJSON *bet_send_message_to_all_active_notaries(cJSON *argjson);
void bet_handle_game(int argc, char **argv);
