void bet_command_info();
void bet_help_dcv_command_usage();
void bet_help_player_command_usage();
void bet_help_cashier_command_usage();
void bet_help_game_command_usage();
void bet_help_withdraw_command_usage();
void bet_help_spendable_command_usage();
void bet_help_extract_tx_data_command_usage();
void bet_help_print_command_usage();
void bet_help_print_id_command_usage();
void bet_help_command(char *command);
void bet_help_raise_registration_dispute_command_usage(void);
void bet_help_register_dealer_command_usage(void);
void bet_help_deregister_dealer_command_usage(void);
