Bet: /root/bet/privatebet/bet.h File Reference
bet.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <arpa/inet.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>
#include "../crypto777/OS_portable.h"
#include <libwebsockets.h>
#include "/usr/local/include/nng/compat/nanomsg/bus.h"
#include "/usr/local/include/nng/compat/nanomsg/nn.h"
#include "/usr/local/include/nng/compat/nanomsg/pair.h"
#include "/usr/local/include/nng/compat/nanomsg/pipeline.h"
#include "/usr/local/include/nng/compat/nanomsg/pubsub.h"
#include "/usr/local/include/nng/compat/nanomsg/reqrep.h"
#include "/usr/local/include/nng/compat/nanomsg/tcp.h"
#include "common.h"
Classes
struct BET_shardsinfo
struct gfshare_ctx_bet
struct privatebet_info
struct privatebet_rawpeerln
struct privatebet_peerln
struct privatebet_vars
struct pair256
struct privatebet_share
struct enc_share
struct deck_player_info
struct deck_dcv_info
struct deck_bvv_info
struct cashier
Macros
#define PORT 9000
Enumerations
enum action_type {
small_blind = 1, big_blind, check, raise,
call, allin, fold
}
enum card_type {
burn_card = 0, hole_card, flop_card_1, flop_card_2,
flop_card_3, turn_card, river_card
}
Functions
bits256 xoverz_donna (bits256 a)
bits256 crecip_donna (bits256 a)
bits256 fmul_donna (bits256 a, bits256 b)
bits256 card_rand256 (int32_t privkeyflag, int8_t index)
struct pair256 deckgen_common (struct pair256 *randcards, int32_t numcards)
struct pair256 deckgen_player (bits256 *playerprivs, bits256 *playercards, int32_t *permis, int32_t numcards)
int32_t sg777_deckgen_vendor (int32_t playerid, bits256 *cardprods, bits256 *finalcards, int32_t numcards, bits256 *playercards, bits256 deckid)
struct pair256 p2p_bvv_init (bits256 *keys, struct pair256 b_key, bits256 *blindings, bits256 *blindedcards, bits256 *finalcards, int32_t numcards, int32_t numplayers, int32_t playerid, bits256 deckid)
bits256 curve25519_fieldelement (bits256 hash)
Variables
struct enc_share * g_shares
struct enc_share * all_g_shares [CARDS777_MAXPLAYERS]
struct privatebet_info * bet_player
struct privatebet_vars * player_vars
Macro Definition Documentation
PORT
#define PORT 9000
Definition at line 45 of file bet.h.
Enumeration Type Documentation
action_type
enum action_type
Enumerator
small_blind
big_blind
check
raise
call
allin
fold
Definition at line 47 of file bet.h.
card_type
enum card_type
Enumerator
burn_card
hole_card
flop_card_1
flop_card_2
flop_card_3
turn_card
river_card
Definition at line 57 of file bet.h.
Function Documentation
card_rand256()
bits256 card_rand256 (int32_t privkeyflag, int8_t index)
Definition at line 232 of file bet.c.
Referenced by deckgen_common().
crecip_donna()
bits256 crecip_donna (bits256 a)
Referenced by bet_decode_card(), and BET_rest_decode_card().
curve25519_fieldelement()
bits256 curve25519_fieldelement (bits256 hash)
Definition at line 226 of file bet.c.
Referenced by bet_decode_card(), BET_rest_decode_card(), and sg777_deckgen_vendor().
deckgen_common()
struct pair256 deckgen_common (struct pair256 * randcards, int32_t numcards)
Definition at line 243 of file bet.c.
References card_rand256(), pair256::priv, and pair256::prod.
Referenced by deckgen_player().
deckgen_player()
struct pair256 deckgen_player (bits256 * playerprivs, bits256 * playercards, int32_t * permis, int32_t numcards)
Definition at line 262 of file bet.c.
References bet_permutation(), deckgen_common(), pair256::priv, and pair256::prod.
Referenced by bet_client_join().
fmul_donna()
bits256 fmul_donna (bits256 a, bits256 b)
Referenced by bet_decode_card(), BET_rest_decode_card(), p2p_bvv_init(), and sg777_deckgen_vendor().
p2p_bvv_init()
struct pair256 p2p_bvv_init (bits256 * keys, struct pair256 b_key, bits256 * blindings, bits256 * blindedcards, bits256 * finalcards, int32_t numcards, int32_t numplayers, int32_t playerid, bits256 deckid)
Definition at line 312 of file bet.c.
References bet_cipher_create(), enc_share::bytes, CARDS777_MAXPLAYERS, deckid, fmul_donna(), gfshare_calc_sharenrs(), gfshare_calc_shares(), permis_b, and sharenrs.
Referenced by bet_bvv_init().
sg777_deckgen_vendor()
int32_t sg777_deckgen_vendor (int32_t playerid, bits256 * cardprods, bits256 * finalcards, int32_t numcards, bits256 * playercards, bits256 deckid)
Definition at line 275 of file bet.c.
References CARDS777_MAXCARDS, curve25519_fieldelement(), deckgen_common2(), fmul_donna(), g_hash, permis_d, pair256::priv, pair256::prod, and xoverz_donna().
Referenced by bet_dcv_init(), and BET_rest_dcv_process_init_p().
xoverz_donna()
bits256 xoverz_donna (bits256 a)
Referenced by bet_client_bvv_init(), bet_decode_card(), BET_rest_decode_card(), and sg777_deckgen_vendor().
Variable Documentation
all_g_shares
struct enc_share* all_g_shares[CARDS777_MAXPLAYERS]
Definition at line 73 of file client.c.
bet_player
struct privatebet_info* bet_player
Definition at line 35 of file bet.c.
Referenced by bet_client_join_res(), and bet_player_frontend().
g_shares
struct enc_share* g_shares
Definition at line 44 of file bet.c.
Referenced by bet_bvv_init(), bet_bvv_reset(), bet_client_bvv_init(), bet_client_give_share(), and bet_get_own_share().
player_vars
struct privatebet_vars* player_vars
Definition at line 36 of file bet.c.
Referenced by bet_player_backend_loop(), and bet_player_frontend().