Bet: privatebet/host.c File Reference
host.c File Reference
#include "host.h"
#include "../log/macrologger.h"
#include "bet.h"
#include "cards777.h"
#include "client.h"
#include "commands.h"
#include "common.h"
#include "network.h"
#include "oracle.h"
#include "payment.h"
#include "poker.h"
#include "states.h"
#include "table.h"
#include "cashier.h"
#include "storage.h"
#include "misc.h"
#include "heartbeat.h"
#include <errno.h>
#include <netinet/in.h>
#include <pthread.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
Macros
#define LWS_PLUGIN_STATIC
Functions
void bet_set_table_id ()
void bet_dcv_lws_write (cJSON *data)
void bet_chat (struct lws *wsi, cJSON *argjson)
void initialize_seat (cJSON *seat_info, char *name, int32_t seat, int32_t chips, int32_t empty, int32_t playing)
int32_t bet_seats (struct lws *wsi, cJSON *argjson)
int32_t bet_game (struct lws *wsi, cJSON *argjson)
int32_t bet_dcv_frontend (struct lws *wsi, cJSON *argjson)
int lws_callback_http_dummy (struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
void sigint_handler (int sig)
void bet_push_dcv_to_gui (cJSON *argjson)
int32_t bet_dcv_deck_init_info (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_init (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_dcv_bvv_join (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_start (struct privatebet_info *bet, int32_t peerid)
cJSON * bet_get_seats_json (int32_t max_players)
int32_t bet_player_join_req (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_send_turn_info (struct privatebet_info *bet, int32_t playerid, int32_t cardid, int32_t card_type)
int32_t bet_dcv_turn (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_relay (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_check_bvv_ready (struct privatebet_info *bet)
static int32_t bet_create_invoice (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_create_betting_invoice (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_check_player_ready (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_receive_card (cJSON *player_card_info, struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_reset_all_dcv_params (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_dcv_reset (struct privatebet_info *bet, struct privatebet_vars *vars)
void bet_game_info (struct privatebet_info *bet, struct privatebet_vars *vars)
static cJSON * payout_tx_data_info (struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_dcv_poker_winner (struct privatebet_info *bet, struct privatebet_vars *vars, int winners[], int pot)
int32_t bet_evaluate_hand (struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_ln_check (struct privatebet_info *bet)
static int32_t bet_award_winner (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static void bet_push_joinInfo (cJSON *argjson, int32_t numplayers)
static int32_t bet_dcv_stack_info_resp (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static void bet_dcv_process_signed_raw_tx (cJSON *argjson)
static int32_t bet_dcv_verify_rand_str (char *rand_str)
static void bet_send_tx_reverse_rqst (cJSON *argjson, struct privatebet_info *bet)
static int32_t bet_dcv_verify_tx (cJSON *argjson, struct privatebet_info *bet)
void bet_init_player_seats_info ()
static int32_t bet_dcv_check_pos_status (cJSON *argjson, struct privatebet_info *bet)
static int32_t bet_dcv_process_join_req (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
static int32_t bet_dcv_process_tx (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars, char *addr)
static void bet_get_dcv_state (cJSON *argjson, struct privatebet_info *bet)
void bet_dcv_backend_thrd (void *_ptr)
void bet_dcv_backend_loop (void *_ptr)
void bet_dcv_frontend_loop (void *_ptr)
Variables
struct lws * wsi_global_host = NULL
int32_t players_joined = 0
int32_t turn = 0
int32_t no_of_cards = 0
int32_t no_of_rounds = 0
int32_t no_of_bets = 0
int32_t card_matrix [CARDS777_MAXPLAYERS][hand_size]
int32_t card_values [CARDS777_MAXPLAYERS][hand_size]
struct deck_dcv_info dcv_info
int32_t player_ready [CARDS777_MAXPLAYERS]
int32_t hole_cards_drawn = 0
int32_t community_cards_drawn = 0
int32_t flop_cards_drawn = 0
int32_t turn_card_drawn = 0
int32_t river_card_drawn = 0
int32_t bet_amount [CARDS777_MAXPLAYERS][CARDS777_MAXROUNDS]
int32_t eval_game_p [CARDS777_MAXPLAYERS]
int32_t eval_game_c [CARDS777_MAXPLAYERS]
char player_chips_address [CARDS777_MAXPLAYERS][64]
char tx_rand_str [CARDS777_MAXPLAYERS][65]
int no_of_rand_str = 0
int32_t invoiceID
char * suit [NSUITS] = { "clubs", "diamonds", "hearts", "spades" }
char * face [NFACES]
struct privatebet_info * bet_dcv = NULL
struct privatebet_vars * dcv_vars = NULL
static int dealerPosition
int32_t no_of_signers
int32_t max_no_of_signers = 2
int32_t is_signed [CARDS777_MAXPLAYERS]
char lws_buf [65536]
int32_t lws_buf_length = 0
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
int32_t no_of_txs = 0
char tx_ids [CARDS777_MAXPLAYERS][100]
int32_t threshold_time = 30
int32_t dcv_data_exists = 0
char dcv_gui_data [8196]
int ws_dcv_connection_status = 0
double dcv_commission_percentage = 0.75
double dev_fund_percentage = 0.25
int32_t req_id_to_player_id_mapping [CARDS777_MAXPLAYERS]
int32_t heartbeat_on = 0
char table_id [65]
int32_t dcv_state = 0
static struct lws_protocols protocols []
static int interrupted
static const struct lws_http_mount mount
Macro Definition Documentation
LWS_PLUGIN_STATIC
#define LWS_PLUGIN_STATIC
Definition at line 42 of file host.c.
Function Documentation
bet_award_winner()
static int32_t bet_award_winner (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 1278 of file host.c.
References CHANNELD_AWAITING_LOCKIN, CHANNELD_NORMAL, dcv_info, ln_get_channel_status(), make_command(), and deck_dcv_info::uri.
Referenced by bet_dcv_backend_thrd().
bet_chat()
void bet_chat (struct lws * wsi, cJSON * argjson)
Definition at line 121 of file host.c.
Referenced by bet_dcv_frontend().
bet_check_bvv_ready()
static int32_t bet_check_bvv_ready (struct privatebet_info * bet) static
Definition at line 586 of file host.c.
References dcv_info, privatebet_info::maxplayers, privatebet_info::pubsock, and deck_dcv_info::uri.
Referenced by bet_dcv_process_join_req().
bet_check_player_ready()
int32_t bet_check_player_ready (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 720 of file host.c.
References privatebet_info::maxplayers, and player_ready.
Referenced by bet_dcv_backend_thrd().
bet_create_betting_invoice()
static int32_t bet_create_betting_invoice (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 664 of file host.c.
References deck_dcv_info::betamount, dcv_info, deck_dcv_info::deckid, invoiceID, make_command(), mchips_msatoshichips, and privatebet_info::pubsock.
Referenced by bet_dcv_backend_thrd().
bet_create_invoice()
static int32_t bet_create_invoice (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 610 of file host.c.
References deck_dcv_info::betamount, dcv_info, deck_dcv_info::deckid, invoiceID, make_command(), and privatebet_info::pubsock.
Referenced by bet_dcv_backend_thrd().
bet_dcv_backend_loop()
void bet_dcv_backend_loop (void * _ptr)
Definition at line 1736 of file host.c.
References bet_dcv_backend_thrd(), bet_permutation(), card_matrix, card_values, dcv_info, deck_dcv_info::dcv_key, dcv_vars, privatebet_vars::dealer, dealerPosition, deck_dcv_info::deckid, hand_size, invoiceID, privatebet_info::maxplayers, deck_dcv_info::maxplayers, deck_dcv_info::numplayers, deck_dcv_info::permis, permis_d, player_ready, pair256::priv, pair256::prod, privatebet_info::pubsock, privatebet_info::pullsock, and privatebet_info::range.
Referenced by bet_dcv_thrd().
bet_dcv_backend_thrd()
void bet_dcv_backend_thrd (void * _ptr)
Definition at line 1635 of file host.c.
References bet_award_winner(), bet_check_player_ready(), bet_create_betting_invoice(), bet_create_invoice(), bet_dcv, bet_dcv_bvv_join(), bet_dcv_deck_init_info(), bet_dcv_init(), bet_dcv_process_join_req(), bet_dcv_process_signed_raw_tx(), bet_dcv_process_tx(), bet_dcv_stack_info_resp(), bet_dcv_start(), bet_dcv_turn(), bet_dcv_update_player_status(), bet_display_current_state(), bet_get_dcv_state(), bet_get_seats_json(), bet_initiate_statemachine(), bet_player_betting_statemachine(), bet_receive_card(), bet_relay(), dcv_info, dcv_vars, privatebet_vars::funds, legacy_m_of_n_msig_addr, privatebet_info::maxplayers, deck_dcv_info::maxplayers, deck_dcv_info::numplayers, and privatebet_info::pubsock.
Referenced by bet_dcv_backend_loop().
bet_dcv_bvv_join()
static int32_t bet_dcv_bvv_join (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 381 of file host.c.
References chips_tx_fee, max_players, privatebet_info::pubsock, and table_stack_in_chips.
Referenced by bet_dcv_backend_thrd().
bet_dcv_check_pos_status()
static int32_t bet_dcv_check_pos_status (cJSON * argjson, struct privatebet_info * bet) static
Definition at line 1502 of file host.c.
References player_seats_info, and privatebet_info::pubsock.
Referenced by bet_dcv_process_join_req().
bet_dcv_deck_init_info()
int32_t bet_dcv_deck_init_info (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 311 of file host.c.
References deck_dcv_info::cardprods, dcv_info, deck_dcv_info::dcvblindcards, deck_dcv_info::deckid, g_hash, deck_dcv_info::numplayers, deck_dcv_info::peerpubkeys, privatebet_info::pubsock, and privatebet_info::range.
Referenced by bet_dcv_backend_thrd().
bet_dcv_frontend()
int32_t bet_dcv_frontend (struct lws * wsi, cJSON * argjson)
Definition at line 197 of file host.c.
References bet_chat(), bet_dcv, bet_game(), bet_get_chips_ln_addr_info(), bet_get_chips_ln_bal_info(), bet_reset_all_dcv_params(), bet_seats(), dcv_vars, and privatebet_info::pubsock.
Referenced by lws_callback_http_dummy().
bet_dcv_frontend_loop()
void bet_dcv_frontend_loop (void * _ptr)
Definition at line 1791 of file host.c.
References dcv_info, interrupted, mount, and protocols.
Referenced by bet_dcv_thrd().
bet_dcv_init()
int32_t bet_dcv_init (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 358 of file host.c.
References bet_dcv_start(), deck_dcv_info::cardprods, CARDS777_MAXCARDS, dcv_info, deck_dcv_info::dcvblindcards, deck_dcv_info::deckid, privatebet_info::maxplayers, deck_dcv_info::numplayers, privatebet_info::range, and sg777_deckgen_vendor().
Referenced by bet_dcv_backend_thrd().
bet_dcv_lws_write()
void bet_dcv_lws_write (cJSON * data)
Definition at line 105 of file host.c.
References dcv_data_exists, dcv_gui_data, ws_dcv_connection_status, and wsi_global_host.
Referenced by bet_push_dcv_to_gui(), and bet_push_joinInfo().
bet_dcv_poker_winner()
static int32_t bet_dcv_poker_winner (struct privatebet_info * bet, struct privatebet_vars * vars, int winners[], int pot) static
Definition at line 1016 of file host.c.
References chips_create_payout_tx(), chips_get_balance_on_address_from_tx(), chips_get_wallet_address(), chips_tx_fee, dcv_commission_percentage, dcv_info, dev_fund_addr, dev_fund_percentage, legacy_m_of_n_msig_addr, privatebet_info::maxplayers, no_of_txs, privatebet_info::numplayers, payout_tx_data_info(), privatebet_vars::player_chips_addrs, privatebet_info::pubsock, req_id_to_player_id_mapping, str_to_hexstr(), tx_data_size, and tx_ids.
Referenced by bet_evaluate_hand().
bet_dcv_process_join_req()
static int32_t bet_dcv_process_join_req (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 1529 of file host.c.
References bet_check_bvv_ready(), bet_dcv_check_pos_status(), bet_ln_check(), bet_player_join_req(), bet_push_joinInfo(), heartbeat_on, privatebet_info::maxplayers, no_of_rand_str, privatebet_info::numplayers, privatebet_vars::player_chips_addrs, req_id_to_player_id_mapping, and tx_rand_str.
Referenced by bet_dcv_backend_thrd().
bet_dcv_process_signed_raw_tx()
static void bet_dcv_process_signed_raw_tx (cJSON * argjson) static
Definition at line 1401 of file host.c.
References chips_publish_multisig_tx(), chips_send_raw_tx(), is_signed, max_no_of_signers, and no_of_signers.
Referenced by bet_dcv_backend_thrd().
bet_dcv_process_tx()
static int32_t bet_dcv_process_tx (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars, char * addr) static
Definition at line 1566 of file host.c.
References bet_dcv_verify_tx(), bet_run_query(), chips_get_balance_on_address_from_tx(), privatebet_vars::funds, mutex, no_of_notaries, no_of_rand_str, normalization_factor, notary_node_ips, notary_status, privatebet_vars::player_chips_addrs, privatebet_info::pubsock, satoshis, satoshis_per_unit, sql_query_size, table_id, threshold_value, tx_rand_str, and tx_unspent.
Referenced by bet_dcv_backend_thrd().
bet_dcv_reset()
void bet_dcv_reset (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 901 of file host.c.
References bet_push_dcv_to_gui(), and bet_reset_all_dcv_params().
Referenced by bet_evaluate_hand().
bet_dcv_stack_info_resp()
static int32_t bet_dcv_stack_info_resp (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 1366 of file host.c.
References chips_tx_fee, legacy_m_of_n_msig_addr, max_players, no_of_notaries, notary_node_ips, notary_status, privatebet_info::pubsock, table_id, table_stack_in_chips, and threshold_value.
Referenced by bet_dcv_backend_thrd().
bet_dcv_start()
int32_t bet_dcv_start (struct privatebet_info * bet, int32_t peerid)
Definition at line 400 of file host.c.
References privatebet_info::pubsock.
Referenced by bet_dcv_backend_thrd(), and bet_dcv_init().
bet_dcv_turn()
int32_t bet_dcv_turn (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 500 of file host.c.
References bet_send_turn_info(), card_matrix, flop_card_1, flop_card_2, flop_card_3, flop_cards_drawn, hole_card, hole_cards_drawn, privatebet_info::maxplayers, no_of_flop_cards, no_of_hole_cards, no_of_river_card, no_of_turn_card, river_card, river_card_drawn, turn_card, and turn_card_drawn.
Referenced by bet_dcv_backend_thrd(), bet_dcv_round_betting(), and bet_receive_card().
bet_dcv_verify_rand_str()
static int32_t bet_dcv_verify_rand_str (char * rand_str) static
Definition at line 1416 of file host.c.
References no_of_rand_str, and tx_rand_str.
bet_dcv_verify_tx()
static int32_t bet_dcv_verify_tx (cJSON * argjson, struct privatebet_info * bet) static
Definition at line 1443 of file host.c.
References bet_dcv, bet_send_tx_reverse_rqst(), chips_check_if_tx_unspent(), chips_extract_data(), chips_get_block_count(), dcv_state, hexstr_to_str(), privatebet_info::maxplayers, mutex, no_of_txs, table_id, tx_data_size, and tx_ids.
Referenced by bet_dcv_process_tx().
bet_evaluate_hand()
int32_t bet_evaluate_hand (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 1094 of file host.c.
References privatebet_vars::bet_actions, bet_dcv_poker_winner(), bet_dcv_reset(), bet_game_info(), card_values, CARDS777_MAXPLAYERS, find_bvv(), fold, hand_size, privatebet_info::maxplayers, no_of_hole_cards, privatebet_vars::pot, privatebet_info::pubsock, privatebet_vars::round, seven_card_draw_score(), and wsi_global_host.
Referenced by bet_dcv_round_betting().
bet_game()
int32_t bet_game (struct lws * wsi, cJSON * argjson)
Definition at line 172 of file host.c.
References big_blind_amount, max_players, and small_blind_amount.
Referenced by bet_dcv_frontend().
bet_game_info()
void bet_game_info (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 911 of file host.c.
References arg_size, privatebet_vars::bet_actions, bet_alloc_args(), bet_dealloc_args(), bet_make_insert_query(), bet_msg_cashier(), bet_run_query(), card_values, hand_size, privatebet_info::maxplayers, no_of_notaries, notary_node_ips, notary_status, privatebet_info::pubsock, privatebet_vars::round, and table_id.
Referenced by bet_evaluate_hand().
bet_get_dcv_state()
static void bet_get_dcv_state (cJSON * argjson, struct privatebet_info * bet) static
Definition at line 1621 of file host.c.
References dcv_state, privatebet_info::maxplayers, players_joined, and privatebet_info::pubsock.
Referenced by bet_dcv_backend_thrd().
bet_get_seats_json()
cJSON* bet_get_seats_json (int32_t max_players)
Definition at line 418 of file host.c.
References initialize_seat(), max_players, and player_seats_info.
Referenced by bet_dcv_backend_thrd(), and bet_player_join_req().
bet_init_player_seats_info()
void bet_init_player_seats_info ()
Definition at line 1491 of file host.c.
References seat_info::chips, seat_info::empty, max_players, player_seats_info, seat_info::playing, and seat_info::seat.
Referenced by bet_reset_all_dcv_params(), and dealer_node_init().
bet_ln_check()
int32_t bet_ln_check (struct privatebet_info * bet)
Definition at line 1249 of file host.c.
References bet_dcv, CHANNELD_AWAITING_LOCKIN, CHANNELD_NORMAL, dcv_info, ln_get_channel_status(), privatebet_info::maxplayers, and deck_dcv_info::uri.
Referenced by bet_dcv_process_join_req().
bet_player_join_req()
int32_t bet_player_join_req (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 433 of file host.c.
References bet_get_seats_json(), seat_info::chips, dcv_info, dealerPosition, seat_info::empty, privatebet_vars::funds, ln_get_uri(), ln_uri_length, privatebet_info::maxplayers, privatebet_info::numplayers, deck_dcv_info::peerpubkeys, player_info, player_seats_info, players_joined, privatebet_info::pubsock, req_id_to_player_id_mapping, and deck_dcv_info::uri.
Referenced by bet_dcv_process_join_req().
bet_push_dcv_to_gui()
void bet_push_dcv_to_gui (cJSON * argjson)
Definition at line 304 of file host.c.
References bet_dcv_lws_write().
Referenced by bet_dcv_reset(), and bet_initiate_statemachine().
bet_push_joinInfo()
static void bet_push_joinInfo (cJSON * argjson, int32_t numplayers) static
Definition at line 1354 of file host.c.
References bet_dcv_lws_write().
Referenced by bet_dcv_process_join_req().
bet_receive_card()
int32_t bet_receive_card (cJSON * player_card_info, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 733 of file host.c.
References bet_dcv_round_betting(), bet_dcv_small_blind(), bet_dcv_turn(), card_matrix, card_values, eval_game_c, eval_game_p, flop_card_1, flop_card_2, flop_card_3, flop_cards_drawn, hole_card, hole_cards_drawn, privatebet_info::maxplayers, no_of_cards, no_of_flop_cards, no_of_hole_cards, no_of_river_card, no_of_turn_card, river_card, river_card_drawn, privatebet_vars::round, turn_card, and turn_card_drawn.
Referenced by bet_dcv_backend_thrd().
bet_relay()
int32_t bet_relay (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 569 of file host.c.
References privatebet_info::pubsock.
Referenced by bet_dcv_backend_thrd(), and bet_player_betting_statemachine().
bet_reset_all_dcv_params()
void bet_reset_all_dcv_params (struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 831 of file host.c.
References privatebet_vars::bet_actions, bet_init_player_seats_info(), bet_permutation(), bet_set_table_id(), privatebet_vars::betamount, card_matrix, card_values, privatebet_info::cardid, CARDS777_MAXROUNDS, community_cards_drawn, dcv_info, deck_dcv_info::dcv_key, dcv_state, privatebet_vars::dealer, dealerPosition, deck_dcv_info::deckid, flop_cards_drawn, privatebet_vars::funds, hand_size, heartbeat_on, hole_cards_drawn, invoiceID, privatebet_vars::last_raise, privatebet_vars::last_turn, privatebet_info::maxplayers, deck_dcv_info::maxplayers, no_of_bets, no_of_cards, no_of_rand_str, no_of_rounds, privatebet_info::no_of_turns, no_of_txs, privatebet_info::numplayers, deck_dcv_info::numplayers, deck_dcv_info::permis, permis_d, player_ready, players_joined, privatebet_vars::pot, pair256::priv, pair256::prod, privatebet_info::range, river_card_drawn, privatebet_vars::round, turn, turn_card_drawn, privatebet_info::turni, privatebet_vars::turni, tx_ids, and tx_rand_str.
Referenced by bet_dcv_frontend(), and bet_dcv_reset().
bet_seats()
int32_t bet_seats (struct lws * wsi, cJSON * argjson)
Definition at line 139 of file host.c.
References bet_dcv, initialize_seat(), max_players, and privatebet_info::pubsock.
Referenced by bet_dcv_frontend().
bet_send_turn_info()
static int32_t bet_send_turn_info (struct privatebet_info * bet, int32_t playerid, int32_t cardid, int32_t card_type) static
Definition at line 481 of file host.c.
References privatebet_info::pubsock.
Referenced by bet_dcv_turn().
bet_send_tx_reverse_rqst()
static void bet_send_tx_reverse_rqst (cJSON * argjson, struct privatebet_info * bet) static
Definition at line 1428 of file host.c.
References dcv_state, privatebet_info::maxplayers, players_joined, and privatebet_info::pubsock.
Referenced by bet_dcv_verify_tx().
bet_set_table_id()
void bet_set_table_id ()
Definition at line 96 of file host.c.
References table_id.
Referenced by bet_reset_all_dcv_params(), and dealer_node_init().
initialize_seat()
void initialize_seat (cJSON * seat_info, char * name, int32_t seat, int32_t chips, int32_t empty, int32_t playing)
Definition at line 130 of file host.c.
Referenced by bet_get_seats_json(), and bet_seats().
lws_callback_http_dummy()
int lws_callback_http_dummy (struct lws * wsi, enum lws_callback_reasons reason, void * user, void * in, size_t len)
Definition at line 235 of file host.c.
References bet_dcv_frontend(), dcv_data_exists, dcv_gui_data, lws_buf, lws_buf_length, ws_dcv_connection_status, and wsi_global_host.
payout_tx_data_info()
static cJSON* payout_tx_data_info (struct privatebet_info * bet, struct privatebet_vars * vars) static
Definition at line 968 of file host.c.
References privatebet_vars::bet_actions, card_values, hand_size, privatebet_info::maxplayers, no_of_notaries, no_of_rand_str, notary_node_ips, notary_status, privatebet_vars::round, table_id, threshold_value, and tx_rand_str.
Referenced by bet_dcv_poker_winner().
sigint_handler()
void sigint_handler (int sig)
Definition at line 299 of file host.c.
References interrupted.
Variable Documentation
bet_amount
int32_t bet_amount[CARDS777_MAXPLAYERS][CARDS777_MAXROUNDS]
Definition at line 54 of file host.c.
Referenced by bet_dcv_round_betting_response(), and bet_player_bet_round().
bet_dcv
struct privatebet_info* bet_dcv = NULL
Definition at line 68 of file host.c.
Referenced by bet_dcv_backend_thrd(), bet_dcv_deinitialize(), bet_dcv_frontend(), bet_dcv_initialize(), bet_dcv_thrd(), bet_dcv_verify_tx(), bet_ln_check(), bet_seats(), and chips_publish_multisig_tx().
card_matrix
int32_t card_matrix[CARDS777_MAXPLAYERS][hand_size]
Definition at line 48 of file host.c.
Referenced by bet_dcv_backend_loop(), bet_dcv_turn(), bet_receive_card(), and bet_reset_all_dcv_params().
card_values
int32_t card_values[CARDS777_MAXPLAYERS][hand_size]
Definition at line 49 of file host.c.
Referenced by bet_dcv_backend_loop(), bet_evaluate_hand(), bet_game_info(), bet_receive_card(), bet_reset_all_dcv_params(), and payout_tx_data_info().
community_cards_drawn
int32_t community_cards_drawn = 0
Definition at line 52 of file host.c.
Referenced by bet_reset_all_dcv_params().
dcv_commission_percentage
double dcv_commission_percentage = 0.75
Definition at line 87 of file host.c.
Referenced by bet_dcv_poker_winner().
dcv_data_exists
int32_t dcv_data_exists = 0
Definition at line 83 of file host.c.
Referenced by bet_dcv_lws_write(), and lws_callback_http_dummy().
dcv_gui_data
char dcv_gui_data[8196]
Definition at line 84 of file host.c.
Referenced by bet_dcv_lws_write(), and lws_callback_http_dummy().
dcv_info
struct deck_dcv_info dcv_info
Definition at line 49 of file host.c.
Referenced by bet_award_winner(), bet_check_bvv_ready(), bet_client_dcv_init(), bet_create_betting_invoice(), bet_create_invoice(), bet_dcv_backend_loop(), bet_dcv_backend_thrd(), bet_dcv_deck_init_info(), bet_dcv_frontend_loop(), bet_dcv_init(), bet_dcv_poker_winner(), bet_ln_check(), bet_player_join_req(), and bet_reset_all_dcv_params().
dcv_state
int32_t dcv_state = 0
Definition at line 94 of file host.c.
Referenced by bet_dcv_verify_tx(), bet_get_dcv_state(), bet_process_find_bvv(), bet_reset_all_dcv_params(), and bet_send_tx_reverse_rqst().
dcv_vars
struct privatebet_vars* dcv_vars = NULL
Definition at line 69 of file host.c.
Referenced by bet_dcv_backend_loop(), bet_dcv_backend_thrd(), bet_dcv_deinitialize(), bet_dcv_frontend(), bet_dcv_initialize(), bet_dcv_player_disconnection_action(), and bet_dcv_publish_player_active_info().
dealerPosition
int dealerPosition static
Definition at line 71 of file host.c.
Referenced by bet_dcv_backend_loop(), bet_player_join_req(), and bet_reset_all_dcv_params().
dev_fund_percentage
double dev_fund_percentage = 0.25
Definition at line 88 of file host.c.
Referenced by bet_dcv_poker_winner().
eval_game_c
int32_t eval_game_c[CARDS777_MAXPLAYERS]
Definition at line 55 of file host.c.
Referenced by bet_receive_card().
eval_game_p
int32_t eval_game_p[CARDS777_MAXPLAYERS]
Definition at line 55 of file host.c.
Referenced by bet_receive_card().
face
char* face[NFACES]
Initial value:
= { "two",  "three", "four", "five",     "six",  "seven", "eight",
                       "nine", "ten",   "jack", "queen", "king", "ace" }
Definition at line 65 of file host.c.
Referenced by rest_display_cards().
flop_cards_drawn
int32_t flop_cards_drawn = 0
Definition at line 52 of file host.c.
Referenced by bet_dcv_turn(), bet_receive_card(), and bet_reset_all_dcv_params().
heartbeat_on
int32_t heartbeat_on = 0
Definition at line 91 of file host.c.
Referenced by bet_dcv_heartbeat_loop(), bet_dcv_process_join_req(), and bet_reset_all_dcv_params().
hole_cards_drawn
int32_t hole_cards_drawn = 0
Definition at line 52 of file host.c.
Referenced by bet_dcv_turn(), bet_receive_card(), and bet_reset_all_dcv_params().
interrupted
int interrupted static
Definition at line 277 of file host.c.
Referenced by bet_dcv_frontend_loop(), and sigint_handler().
invoiceID
int32_t invoiceID
Definition at line 62 of file host.c.
Referenced by bet_create_betting_invoice(), bet_create_invoice(), bet_dcv_backend_loop(), and bet_reset_all_dcv_params().
is_signed
int32_t is_signed[CARDS777_MAXPLAYERS]
Definition at line 72 of file host.c.
Referenced by bet_dcv_process_signed_raw_tx().
lws_buf
char lws_buf[65536]
Definition at line 74 of file host.c.
Referenced by lws_callback_http_dummy().
lws_buf_length
int32_t lws_buf_length = 0
Definition at line 75 of file host.c.
Referenced by lws_callback_http_dummy().
max_no_of_signers
int32_t max_no_of_signers = 2
Definition at line 72 of file host.c.
Referenced by bet_dcv_process_signed_raw_tx().
mount
const struct lws_http_mount mount static
Initial value:
= {
         NULL,
         "/",
         "./mount-origin",
         "index.html",
         NULL,
         NULL,
         NULL,
         NULL,
         0,
         0,
         0,
         0,
         0,
         0,
         LWSMPRO_FILE,
         1,
         NULL,
}
Definition at line 277 of file host.c.
Referenced by bet_dcv_frontend_loop().
mutex
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 76 of file host.c.
Referenced by bet_dcv_process_tx(), and bet_dcv_verify_tx().
no_of_bets
int32_t no_of_bets = 0
Definition at line 47 of file host.c.
Referenced by bet_reset_all_dcv_params().
no_of_cards
int32_t no_of_cards = 0
Definition at line 47 of file host.c.
Referenced by bet_receive_card(), and bet_reset_all_dcv_params().
no_of_rand_str
int no_of_rand_str = 0
Definition at line 60 of file host.c.
Referenced by bet_dcv_process_join_req(), bet_dcv_process_tx(), bet_dcv_verify_rand_str(), bet_reset_all_dcv_params(), and payout_tx_data_info().
no_of_rounds
int32_t no_of_rounds = 0
Definition at line 47 of file host.c.
Referenced by bet_reset_all_dcv_params().
no_of_signers
int32_t no_of_signers
Definition at line 72 of file host.c.
Referenced by bet_dcv_process_signed_raw_tx().
no_of_txs
int32_t no_of_txs = 0
Definition at line 78 of file host.c.
Referenced by bet_dcv_poker_winner(), bet_dcv_verify_tx(), bet_reset_all_dcv_params(), check_if_tx_exists(), chips_create_payout_tx(), chips_create_tx_from_tx_list(), and chips_spend_msig_txs().
player_chips_address
char player_chips_address[CARDS777_MAXPLAYERS][64]
Definition at line 57 of file host.c.
player_ready
int32_t player_ready[CARDS777_MAXPLAYERS]
Definition at line 51 of file host.c.
Referenced by bet_check_player_ready(), bet_dcv_backend_loop(), bet_player_ready(), and bet_reset_all_dcv_params().
players_joined
int32_t players_joined = 0
Definition at line 46 of file host.c.
Referenced by bet_get_dcv_state(), bet_player_join_req(), bet_reset_all_dcv_params(), and bet_send_tx_reverse_rqst().
protocols
struct lws_protocols protocols[] static
Initial value:
= {
        { "http", lws_callback_http_dummy, 0, 0 },
        { NULL, NULL, 0, 0 }
}
Definition at line 235 of file host.c.
Referenced by bet_dcv_frontend_loop().
req_id_to_player_id_mapping
int32_t req_id_to_player_id_mapping[CARDS777_MAXPLAYERS]
Definition at line 90 of file host.c.
Referenced by bet_dcv_poker_winner(), bet_dcv_process_join_req(), and bet_player_join_req().
river_card_drawn
int32_t river_card_drawn = 0
Definition at line 53 of file host.c.
Referenced by bet_dcv_turn(), bet_receive_card(), and bet_reset_all_dcv_params().
suit
char* suit[NSUITS] = { "clubs", "diamonds", "hearts", "spades" }
Definition at line 64 of file host.c.
Referenced by cardstr(), and rest_display_cards().
table_id
char table_id[65]
Definition at line 93 of file host.c.
Referenced by bet_dcv_process_tx(), bet_dcv_stack_info_resp(), bet_dcv_verify_tx(), bet_game_info(), bet_player_handle_stack_info_resp(), bet_player_process_game_info(), bet_player_wallet_info(), bet_set_table_id(), chips_create_payout_tx(), chips_sign_msig_tx(), chips_sign_msig_tx_of_table_id(), payout_tx_data_info(), and sqlite3_check_if_table_id_exists().
threshold_time
int32_t threshold_time = 30
Definition at line 81 of file host.c.
turn
int32_t turn = 0
Definition at line 47 of file host.c.
Referenced by bet_reset_all_dcv_params().
turn_card_drawn
int32_t turn_card_drawn = 0
Definition at line 52 of file host.c.
Referenced by bet_dcv_turn(), bet_receive_card(), and bet_reset_all_dcv_params().
tx_ids
char tx_ids[CARDS777_MAXPLAYERS][100]
Definition at line 79 of file host.c.
Referenced by bet_dcv_poker_winner(), bet_dcv_verify_tx(), bet_reset_all_dcv_params(), bet_resolve_game_dispute(), bet_reverse_disputed_tx(), check_if_tx_exists(), chips_create_payout_tx(), chips_create_tx_from_tx_list(), and chips_spend_msig_txs().
tx_rand_str
char tx_rand_str[CARDS777_MAXPLAYERS][65]
Definition at line 59 of file host.c.
Referenced by bet_dcv_process_join_req(), bet_dcv_process_tx(), bet_dcv_verify_rand_str(), bet_reset_all_dcv_params(), and payout_tx_data_info().
ws_dcv_connection_status
int ws_dcv_connection_status = 0
Definition at line 85 of file host.c.
Referenced by bet_dcv_lws_write(), and lws_callback_http_dummy().
wsi_global_host
struct lws* wsi_global_host = NULL
Definition at line 44 of file host.c.
Referenced by bet_dcv_lws_write(), bet_evaluate_hand(), and lws_callback_http_dummy().