Bet: /root/bet/privatebet/gfshare.h File Reference
gfshare.h File Reference
#include "bet.h"
Functions
void libgfshare_init ()
struct gfshare_ctx_bet * _gfshare_init_core (uint8_t *sharenrs, uint32_t sharecount, uint8_t threshold, uint32_t size, void *space, int32_t spacesize)
struct gfshare_ctx_bet * gfshare_initenc (uint8_t *sharenrs, uint32_t sharecount, uint8_t threshold, uint32_t size, void *space, int32_t spacesize)
struct gfshare_ctx_bet * gfshare_initdec (uint8_t *sharenrs, uint32_t sharecount, uint32_t size, void *space, int32_t spacesize)
struct gfshare_ctx_bet * gfshare_sg777_initdec (uint8_t *sharenrs, uint32_t sharecount, uint8_t threshold, uint32_t size, void *space, int32_t spacesize)
void gfshare_free (struct gfshare_ctx_bet *ctx)
void gfshare_enc_setsecret (struct gfshare_ctx_bet *ctx, uint8_t *secret)
void gfshare_encgetshare (uint8_t *_logs, uint8_t *_exps, struct gfshare_ctx_bet *ctx, uint8_t sharenr, uint8_t *share)
void gfshare_dec_newshares (struct gfshare_ctx_bet *ctx, uint8_t *sharenrs)
void gfshare_dec_giveshare (struct gfshare_ctx_bet *ctx, uint8_t sharenr, uint8_t *share)
void gfshare_decextract (uint8_t *_logs, uint8_t *_exps, struct gfshare_ctx_bet *ctx, uint8_t *secretbuf)
int32_t gfshare_calc_sharenrs (uint8_t *sharenrs, int32_t N, uint8_t *data, int32_t datasize)
int32_t gfshare_init_sharenrs (uint8_t sharenrs[255], uint8_t *orig, int32_t m, int32_t n)
uint8_t * gfshare_recoverdata (uint8_t *shares[], uint8_t *sharenrs, int32_t M, uint8_t *recover, int32_t datasize, int32_t N)
void gfshare_calc_share (uint8_t *buffer, int32_t size, int32_t M, uint32_t ilog, uint8_t *share)
void gfshare_calc_shares (uint8_t *shares, uint8_t *secret, int32_t size, int32_t width, int32_t M, int32_t N, uint8_t *sharenrs, uint8_t *space, int32_t spacesize)
Function Documentation
_gfshare_init_core()
struct gfshare_ctx_bet* _gfshare_init_core (uint8_t * sharenrs, uint32_t sharecount, uint8_t threshold, uint32_t size, void * space, int32_t spacesize)
Definition at line 61 of file gfshare.c.
References gfshare_ctx_bet::allocsize, gfshare_ctx_bet::buffersize, gfshare_ctx_bet::sharecount, gfshare_ctx_bet::sharenrs, gfshare_ctx_bet::size, and gfshare_ctx_bet::threshold.
Referenced by gfshare_initdec(), gfshare_initenc(), and gfshare_sg777_initdec().
gfshare_calc_share()
void gfshare_calc_share (uint8_t * buffer, int32_t size, int32_t M, uint32_t ilog, uint8_t * share)
Definition at line 337 of file gfshare.c.
References BET_exps, BET_logs, and gfshare_ctx_bet::size.
Referenced by gfshare_calc_shares().
gfshare_calc_sharenrs()
int32_t gfshare_calc_sharenrs (uint8_t * sharenrs, int32_t N, uint8_t * data, int32_t datasize)
Definition at line 224 of file gfshare.c.
Referenced by bet_decode_card(), and p2p_bvv_init().
gfshare_calc_shares()
void gfshare_calc_shares (uint8_t * shares, uint8_t * secret, int32_t size, int32_t width, int32_t M, int32_t N, uint8_t * sharenrs, uint8_t * space, int32_t spacesize)
Definition at line 354 of file gfshare.c.
References BET_logs, gfshare_ctx_bet::buffer, and gfshare_calc_share().
Referenced by p2p_bvv_init().
gfshare_dec_giveshare()
void gfshare_dec_giveshare (struct gfshare_ctx_bet * ctx, uint8_t sharenr, uint8_t * share)
Definition at line 178 of file gfshare.c.
References gfshare_ctx_bet::buffer, and gfshare_ctx_bet::size.
Referenced by gfshare_recoverdata().
gfshare_dec_newshares()
void gfshare_dec_newshares (struct gfshare_ctx_bet * ctx, uint8_t * sharenrs)
Definition at line 171 of file gfshare.c.
References gfshare_ctx_bet::sharecount, and gfshare_ctx_bet::sharenrs.
Referenced by gfshare_recoverdata().
gfshare_decextract()
void gfshare_decextract (uint8_t * _logs, uint8_t * _exps, struct gfshare_ctx_bet * ctx, uint8_t * secretbuf)
Definition at line 185 of file gfshare.c.
References BET_exps, BET_logs, gfshare_ctx_bet::buffer, gfshare_ctx_bet::sharecount, gfshare_ctx_bet::sharenrs, and gfshare_ctx_bet::size.
Referenced by gfshare_recoverdata().
gfshare_enc_setsecret()
void gfshare_enc_setsecret (struct gfshare_ctx_bet * ctx, uint8_t * secret)
Definition at line 136 of file gfshare.c.
References gfshare_ctx_bet::buffer, gfshare_ctx_bet::size, and gfshare_ctx_bet::threshold.
gfshare_encgetshare()
void gfshare_encgetshare (uint8_t * _logs, uint8_t * _exps, struct gfshare_ctx_bet * ctx, uint8_t sharenr, uint8_t * share)
Definition at line 145 of file gfshare.c.
References BET_exps, BET_logs, gfshare_ctx_bet::buffer, gfshare_ctx_bet::sharenrs, gfshare_ctx_bet::size, and gfshare_ctx_bet::threshold.
gfshare_free()
void gfshare_free (struct gfshare_ctx_bet * ctx)
Definition at line 122 of file gfshare.c.
References gfshare_ctx_bet::allocsize, gfshare_ctx_bet::buffer, gfshare_ctx_bet::buffersize, gfshare_ctx_bet::sharecount, and gfshare_ctx_bet::sharenrs.
Referenced by gfshare_recoverdata().
gfshare_init_sharenrs()
int32_t gfshare_init_sharenrs (uint8_t sharenrs[255], uint8_t * orig, int32_t m, int32_t n)
Definition at line 252 of file gfshare.c.
gfshare_initdec()
struct gfshare_ctx_bet* gfshare_initdec (uint8_t * sharenrs, uint32_t sharecount, uint32_t size, void * space, int32_t spacesize)
Definition at line 102 of file gfshare.c.
References _gfshare_init_core(), and gfshare_ctx_bet::threshold.
Referenced by gfshare_recoverdata().
gfshare_initenc()
struct gfshare_ctx_bet* gfshare_initenc (uint8_t * sharenrs, uint32_t sharecount, uint8_t threshold, uint32_t size, void * space, int32_t spacesize)
Definition at line 85 of file gfshare.c.
References _gfshare_init_core(), and gfshare_ctx_bet::sharecount.
gfshare_recoverdata()
uint8_t* gfshare_recoverdata (uint8_t * shares[], uint8_t * sharenrs, int32_t M, uint8_t * recover, int32_t datasize, int32_t N)
Definition at line 314 of file gfshare.c.
References BET_exps, BET_logs, gfshare_dec_giveshare(), gfshare_dec_newshares(), gfshare_decextract(), gfshare_free(), and gfshare_initdec().
Referenced by bet_decode_card().
gfshare_sg777_initdec()
struct gfshare_ctx_bet* gfshare_sg777_initdec (uint8_t * sharenrs, uint32_t sharecount, uint8_t threshold, uint32_t size, void * space, int32_t spacesize)
Definition at line 112 of file gfshare.c.
References _gfshare_init_core(), and gfshare_ctx_bet::threshold.
libgfshare_init()
void libgfshare_init ()
Definition at line 46 of file gfshare.c.
References BET_exps, and BET_logs.
Referenced by main().