Bet: privatebet/heartbeat.h File Reference
heartbeat.h File Reference
#include "bet.h"
Functions
void bet_dcv_heartbeat_loop (void *_ptr)
void bet_dcv_update_player_status (cJSON *argjson)
void bet_dcv_heartbeat_thread (struct privatebet_info *bet)
Function Documentation
bet_dcv_heartbeat_loop()
void bet_dcv_heartbeat_loop (void * _ptr)
Definition at line 89 of file heartbeat.c.
References bet_dcv_publish_player_active_info(), bet_dcv_reset_player_status(), heartbeat_on, and privatebet_info::pubsock.
Referenced by bet_dcv_heartbeat_thread(), and bet_dcv_thrd().
bet_dcv_heartbeat_thread()
void bet_dcv_heartbeat_thread (struct privatebet_info * bet)
Definition at line 119 of file heartbeat.c.
References bet_dcv_heartbeat_loop().
bet_dcv_update_player_status()
void bet_dcv_update_player_status (cJSON * argjson)
Definition at line 111 of file heartbeat.c.
References player_status.
Referenced by bet_dcv_backend_thrd().