Bet: privatebet/states.c File Reference
states.c File Reference
#include "states.h"
#include "bet.h"
#include "client.h"
#include "common.h"
#include "host.h"
#include "network.h"
#include "payment.h"
#include "table.h"
Functions
int32_t bet_initiate_statemachine (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_next_turn (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
Function: BET_DCV_next_turn.
int32_t bet_dcv_round_betting (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_round_betting_response (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_big_blind_bet (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_big_blind (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_small_blind_bet (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_small_blind (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_betting_statemachine (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_display_current_state (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_small_blind_bet (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_big_blind_bet (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_dealer_info (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_small_blind (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_big_blind (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_round_betting (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_player_round_betting_response (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
Variables
char action_str [8][100] = { "", "small_blind", "big_blind", "check", "raise", "call", "allin", "fold" }
Function Documentation
bet_dcv_big_blind()
int32_t bet_dcv_big_blind (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 367 of file states.c.
References privatebet_vars::last_turn, privatebet_info::maxplayers, privatebet_vars::pot, privatebet_info::pubsock, privatebet_vars::small_blind, and privatebet_vars::turni.
Referenced by bet_dcv_small_blind_bet().
bet_dcv_big_blind_bet()
int32_t bet_dcv_big_blind_bet (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 349 of file states.c.
References privatebet_vars::bet_actions, bet_dcv_round_betting(), privatebet_vars::betamount, big_blind, privatebet_vars::big_blind, privatebet_vars::funds, and privatebet_vars::pot.
Referenced by bet_player_betting_statemachine().
bet_dcv_next_turn()
int32_t bet_dcv_next_turn (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Function: BET_DCV_next_turn.
Parameters:
           structure:  cJSON *argjson contains the information about
current active turn of the player structure: struct privatebet_info *bet contains deck and player information structure: privatebet_vars *vars contains the game information
Return Value :
           0 --> bet->maxplayers : It indicates there a valid turn exists
in the game. -1 : No valid turn exists
Description:
           This function identifies if there is any valid turn possible
during the game, if any valid turn exists it returns the index of the player if not it returns -1
Definition at line 92 of file states.c.
References allin, privatebet_vars::bet_actions, privatebet_vars::betamount, big_blind, call, check, fold, privatebet_vars::funds, privatebet_info::maxplayers, privatebet_vars::round, small_blind, and privatebet_vars::turni.
Referenced by bet_dcv_round_betting().
bet_dcv_round_betting()
int32_t bet_dcv_round_betting (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 132 of file states.c.
References allin, privatebet_vars::bet_actions, bet_dcv_next_turn(), bet_dcv_turn(), bet_evaluate_hand(), privatebet_vars::betamount, big_blind, big_blind_amount, call, CARDS777_MAXROUNDS, check, privatebet_vars::dealer, fold, privatebet_vars::funds, privatebet_vars::last_raise, privatebet_vars::last_turn, privatebet_info::maxplayers, privatebet_vars::pot, privatebet_info::pubsock, privatebet_vars::round, and privatebet_vars::turni.
Referenced by bet_dcv_big_blind_bet(), bet_dcv_round_betting_response(), and bet_receive_card().
bet_dcv_round_betting_response()
int32_t bet_dcv_round_betting_response (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 296 of file states.c.
References allin, privatebet_vars::bet_actions, bet_amount, bet_dcv_round_betting(), privatebet_vars::betamount, call, CARDS777_MAXROUNDS, check, fold, privatebet_vars::funds, privatebet_vars::last_raise, privatebet_info::maxplayers, privatebet_vars::pot, and privatebet_vars::round.
Referenced by bet_dcv_publish_player_active_info(), and bet_player_betting_statemachine().
bet_dcv_small_blind()
int32_t bet_dcv_small_blind (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 413 of file states.c.
References privatebet_vars::dealer, privatebet_vars::last_turn, privatebet_info::maxplayers, privatebet_vars::pot, privatebet_info::pubsock, privatebet_vars::round, and privatebet_vars::turni.
Referenced by bet_receive_card().
bet_dcv_small_blind_bet()
int32_t bet_dcv_small_blind_bet (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 395 of file states.c.
References privatebet_vars::bet_actions, bet_dcv_big_blind(), privatebet_vars::betamount, privatebet_vars::funds, privatebet_vars::pot, small_blind, and privatebet_vars::small_blind.
Referenced by bet_player_betting_statemachine().
bet_display_current_state()
int32_t bet_display_current_state (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 511 of file states.c.
References privatebet_vars::bet_actions, privatebet_vars::betamount, big_blind, privatebet_vars::big_blind, call, CARDS777_MAXROUNDS, check, fold, privatebet_info::maxplayers, small_blind, and privatebet_vars::small_blind.
Referenced by bet_dcv_backend_thrd(), and bet_player_backend().
bet_initiate_statemachine()
int32_t bet_initiate_statemachine (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 30 of file states.c.
References privatebet_vars::bet_actions, bet_push_dcv_to_gui(), privatebet_vars::betamount, CARDS777_MAXROUNDS, privatebet_vars::dealer, privatebet_vars::last_raise, privatebet_vars::last_turn, privatebet_info::maxplayers, privatebet_vars::pot, privatebet_info::pubsock, privatebet_vars::round, and privatebet_vars::turni.
Referenced by bet_dcv_backend_thrd().
bet_player_betting_statemachine()
int32_t bet_player_betting_statemachine (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 444 of file states.c.
References bet_dcv_big_blind_bet(), bet_dcv_round_betting_response(), bet_dcv_small_blind_bet(), bet_player_big_blind(), bet_player_big_blind_bet(), bet_player_round_betting_response(), bet_player_small_blind(), bet_player_small_blind_bet(), bet_relay(), privatebet_vars::betamount, display_cards(), privatebet_vars::funds, privatebet_info::maxplayers, privatebet_info::myplayerid, player_lws_write(), and privatebet_info::pubsock.
Referenced by bet_dcv_backend_thrd(), and bet_player_backend().
bet_player_big_blind()
int32_t bet_player_big_blind (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 654 of file states.c.
References bet_player_invoice_pay(), privatebet_vars::betamount, big_blind_amount, privatebet_info::myplayerid, privatebet_vars::player_funds, player_lws_write(), privatebet_info::pushsock, and privatebet_vars::round.
Referenced by bet_player_betting_statemachine().
bet_player_big_blind_bet()
int32_t bet_player_big_blind_bet (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 562 of file states.c.
References privatebet_vars::bet_actions, privatebet_vars::betamount, big_blind, privatebet_vars::big_blind, privatebet_info::maxplayers, privatebet_vars::pot, and privatebet_vars::turni.
Referenced by bet_player_betting_statemachine().
bet_player_dealer_info()
int32_t bet_player_dealer_info (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 578 of file states.c.
References privatebet_vars::bet_actions, bet_push_client(), privatebet_vars::betamount, CARDS777_MAXROUNDS, privatebet_vars::dealer, privatebet_info::maxplayers, privatebet_info::myplayerid, privatebet_vars::pot, privatebet_info::pushsock, and privatebet_vars::turni.
Referenced by bet_player_backend().
bet_player_round_betting()
int32_t bet_player_round_betting (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 691 of file states.c.
References action_str, allin, privatebet_vars::bet_actions, bet_player_invoice_request(), privatebet_vars::betamount, call, privatebet_vars::player_funds, and privatebet_info::pushsock.
Referenced by bet_player_frontend().
bet_player_round_betting_response()
int32_t bet_player_round_betting_response (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 777 of file states.c.
References allin, privatebet_vars::bet_actions, bet_push_client(), privatebet_vars::betamount, call, check, fold, privatebet_vars::funds, privatebet_info::maxplayers, privatebet_info::myplayerid, privatebet_vars::pot, and privatebet_vars::round.
Referenced by bet_player_betting_statemachine().
bet_player_small_blind()
int32_t bet_player_small_blind (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 616 of file states.c.
References bet_player_invoice_pay(), privatebet_vars::betamount, privatebet_info::myplayerid, privatebet_vars::player_funds, player_lws_write(), privatebet_info::pushsock, privatebet_vars::round, and small_blind_amount.
Referenced by bet_player_betting_statemachine().
bet_player_small_blind_bet()
int32_t bet_player_small_blind_bet (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 546 of file states.c.
References privatebet_vars::bet_actions, privatebet_vars::betamount, privatebet_info::maxplayers, privatebet_vars::pot, small_blind, privatebet_vars::small_blind, and privatebet_vars::turni.
Referenced by bet_player_betting_statemachine().
Variable Documentation
action_str
char action_str[8][100] = { "", "small_blind", "big_blind", "check", "raise", "call", "allin", "fold" }
Definition at line 24 of file states.c.
Referenced by bet_player_round_betting(), and rest_display_cards().