Bet: /root/bet/privatebet/table.c File Reference
table.c File Reference
#include "table.h"
#include "bet.h"
#include "common.h"
#include "network.h"
Functions
void bet_info_set (struct privatebet_info *bet, char *game, int32_t range, int32_t numrounds, int32_t maxplayers)
Function Documentation
bet_info_set()
void bet_info_set (struct privatebet_info * bet, char * game, int32_t range, int32_t numrounds, int32_t maxplayers)
Definition at line 20 of file table.c.
References privatebet_info::game, privatebet_info::maxplayers, privatebet_info::numrounds, and privatebet_info::range.
Referenced by bet_bvv_initialize(), bet_dcv_initialize(), and bet_player_initialize().