Bet: /root/bet/privatebet/poker.c File Reference
poker.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Classes
struct CardPileType
Macros
#define CLUB_SUIT (1)
#define DIAMOND_SUIT (2)
#define HEART_SUIT (4)
#define SPADE_SUIT (8)
#define RANK_SHL (27)
#define SUBR_SHL (13)
#define SUBR_SHLMASK ((1 << SUBR_SHL) - 1)
#define STRAIGHT_FLUSH_SCORE (8 << RANK_SHL)
#define FOUR_KIND_SCORE (7 << RANK_SHL)
#define FULL_HOUSE_SCORE (6 << RANK_SHL)
#define FLUSH_SCORE (5 << RANK_SHL)
#define STRAIGHT_SCORE (4 << RANK_SHL)
#define THREE_KIND_SCORE (3 << RANK_SHL)
#define TWO_PAIR_SCORE (2 << RANK_SHL)
#define TWO_KIND_SCORE (1 << RANK_SHL)
#define ONE_PAIR_SCORE (TWO_KIND_SCORE)
#define SevenCardDrawFlushScore(f) (FLUSH_SCORE + ((f) >> SUBR_SHL))
Typedefs
typedef uint8_t u8
typedef int8_t s8
typedef uint32_t u32
typedef int32_t s32
Functions
int32_t cardstr (char *cardstr, uint8_t card)
static u32 FiveCardDrawScoreFast (u32 c0, u32 c1, u32 c2, u32 c3, u32 c4, u32 u)
u32 five_card_draw_score (const u8 *h)
static u32 SevenCardDrawFlush (const u8 *h, const u32 c[7])
u32 seven_card_draw_score (const u8 *h)
u32 SevenCardDrawScoreSlow (const u8 *h)
static void Shuffle (CardPileType *c)
static int32_t Deal (CardPileType *h, CardPileType *d, int32_t n)
static void InitDeck (CardPileType *deck)
static void DisplayCard (u8 c, char out[])
void DisplayHand5 (const CardPileType *h)
void set_cardstr (char *cardstr, uint32_t c)
uint32_t set_handstr (char *handstr, uint8_t cards[7], int32_t verbose)
void DisplayHand7 (char *handstr, uint8_t *cards)
void poker_test ()
Variables
static char * handstrs [16]
static char * kickerstrs [16]
static u32 CardValue [52]
static u32 CardSuit [52]
static u32 CardSuitIdx [52]
static u32 CardMask [52]
Macro Definition Documentation
CLUB_SUIT
#define CLUB_SUIT (1)
Definition at line 11 of file poker.c.
DIAMOND_SUIT
#define DIAMOND_SUIT (2)
Definition at line 12 of file poker.c.
FLUSH_SCORE
#define FLUSH_SCORE (5 << RANK_SHL)
Definition at line 23 of file poker.c.
Referenced by FiveCardDrawScoreFast().
FOUR_KIND_SCORE
#define FOUR_KIND_SCORE (7 << RANK_SHL)
Definition at line 21 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
FULL_HOUSE_SCORE
#define FULL_HOUSE_SCORE (6 << RANK_SHL)
Definition at line 22 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
HEART_SUIT
#define HEART_SUIT (4)
Definition at line 13 of file poker.c.
ONE_PAIR_SCORE
#define ONE_PAIR_SCORE (TWO_KIND_SCORE)
Definition at line 29 of file poker.c.
RANK_SHL
#define RANK_SHL (27)
Definition at line 16 of file poker.c.
Referenced by set_handstr().
SevenCardDrawFlushScore
#define SevenCardDrawFlushScore (f) (FLUSH_SCORE + ((f) >> SUBR_SHL))
Definition at line 268 of file poker.c.
Referenced by seven_card_draw_score().
SPADE_SUIT
#define SPADE_SUIT (8)
Definition at line 14 of file poker.c.
STRAIGHT_FLUSH_SCORE
#define STRAIGHT_FLUSH_SCORE (8 << RANK_SHL)
Definition at line 20 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
STRAIGHT_SCORE
#define STRAIGHT_SCORE (4 << RANK_SHL)
Definition at line 24 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
SUBR_SHL
#define SUBR_SHL (13)
Definition at line 17 of file poker.c.
Referenced by DisplayHand7(), FiveCardDrawScoreFast(), set_handstr(), seven_card_draw_score(), and SevenCardDrawFlush().
SUBR_SHLMASK
#define SUBR_SHLMASK ((1 << SUBR_SHL) - 1)
Definition at line 18 of file poker.c.
Referenced by DisplayHand7(), and set_handstr().
THREE_KIND_SCORE
#define THREE_KIND_SCORE (3 << RANK_SHL)
Definition at line 25 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
TWO_KIND_SCORE
#define TWO_KIND_SCORE (1 << RANK_SHL)
Definition at line 27 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
TWO_PAIR_SCORE
#define TWO_PAIR_SCORE (2 << RANK_SHL)
Definition at line 26 of file poker.c.
Referenced by FiveCardDrawScoreFast(), and seven_card_draw_score().
Typedef Documentation
s32
typedef int32_t s32
Definition at line 34 of file poker.c.
s8
typedef int8_t s8
Definition at line 32 of file poker.c.
u32
typedef uint32_t u32
Definition at line 33 of file poker.c.
u8
typedef uint8_t u8
Definition at line 31 of file poker.c.
Function Documentation
cardstr()
int32_t cardstr (char * cardstr, uint8_t card)
Definition at line 72 of file poker.c.
References suit.
Referenced by set_handstr().
Deal()
static int32_t Deal (CardPileType * h, CardPileType * d, int32_t n) static
Definition at line 534 of file poker.c.
References CardPileType::entry, and CardPileType::len.
Referenced by poker_test().
DisplayCard()
static void DisplayCard (u8 c, char out[]) static
Definition at line 553 of file poker.c.
References CardSuit, and CardValue.
Referenced by DisplayHand5(), and DisplayHand7().
DisplayHand5()
void DisplayHand5 (const CardPileType * h)
Definition at line 566 of file poker.c.
References DisplayCard(), CardPileType::entry, and five_card_draw_score().
DisplayHand7()
void DisplayHand7 (char * handstr, uint8_t * cards)
Definition at line 661 of file poker.c.
References DisplayCard(), set_handstr(), seven_card_draw_score(), SevenCardDrawScoreSlow(), SUBR_SHL, and SUBR_SHLMASK.
Referenced by poker_test().
five_card_draw_score()
u32 five_card_draw_score (const u8 * h)
Definition at line 174 of file poker.c.
References CardMask, CardSuit, and FiveCardDrawScoreFast().
Referenced by DisplayHand5(), and SevenCardDrawScoreSlow().
FiveCardDrawScoreFast()
static u32 FiveCardDrawScoreFast (u32 c0, u32 c1, u32 c2, u32 c3, u32 c4, u32 u) static
Definition at line 97 of file poker.c.
References FLUSH_SCORE, FOUR_KIND_SCORE, FULL_HOUSE_SCORE, STRAIGHT_FLUSH_SCORE, STRAIGHT_SCORE, SUBR_SHL, THREE_KIND_SCORE, TWO_KIND_SCORE, and TWO_PAIR_SCORE.
Referenced by five_card_draw_score().
InitDeck()
static void InitDeck (CardPileType * deck) static
Definition at line 545 of file poker.c.
References CardPileType::entry, and CardPileType::len.
Referenced by poker_test().
poker_test()
void poker_test ()
Definition at line 680 of file poker.c.
References Deal(), DisplayHand7(), InitDeck(), seven_card_draw_score(), and Shuffle().
set_cardstr()
void set_cardstr (char * cardstr, uint32_t c)
Definition at line 579 of file poker.c.
Referenced by set_handstr().
set_handstr()
uint32_t set_handstr (char * handstr, uint8_t cards[7], int32_t verbose)
Definition at line 598 of file poker.c.
References cardstr(), handstrs, kickerstrs, RANK_SHL, set_cardstr(), seven_card_draw_score(), SUBR_SHL, and SUBR_SHLMASK.
Referenced by DisplayHand7().
seven_card_draw_score()
u32 seven_card_draw_score (const u8 * h)
Definition at line 270 of file poker.c.
References CardMask, FOUR_KIND_SCORE, FULL_HOUSE_SCORE, SevenCardDrawFlush(), SevenCardDrawFlushScore, STRAIGHT_FLUSH_SCORE, STRAIGHT_SCORE, SUBR_SHL, THREE_KIND_SCORE, TWO_KIND_SCORE, and TWO_PAIR_SCORE.
Referenced by bet_evaluate_hand(), DisplayHand7(), poker_test(), and set_handstr().
SevenCardDrawFlush()
static u32 SevenCardDrawFlush (const u8 * h, const u32 c[7]) static
Definition at line 192 of file poker.c.
References CardSuitIdx, and SUBR_SHL.
Referenced by seven_card_draw_score().
SevenCardDrawScoreSlow()
u32 SevenCardDrawScoreSlow (const u8 * h)
Definition at line 490 of file poker.c.
References five_card_draw_score().
Referenced by DisplayHand7().
Shuffle()
static void Shuffle (CardPileType * c) static
Definition at line 518 of file poker.c.
References CardPileType::entry, and CardPileType::len.
Referenced by poker_test().
Variable Documentation
CardMask
u32 CardMask[52] static
Initial value:
= {
        1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0x1000,
        1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0x1000,
        1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0x1000,
        1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0x1000
}
Definition at line 90 of file poker.c.
Referenced by five_card_draw_score(), and seven_card_draw_score().
CardSuit
u32 CardSuit[52] static
Initial value:
= { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8 }
Definition at line 67 of file poker.c.
Referenced by DisplayCard(), and five_card_draw_score().
CardSuitIdx
u32 CardSuitIdx[52] static
Initial value:
= { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                               1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                               2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                               3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3 }
Definition at line 85 of file poker.c.
Referenced by SevenCardDrawFlush().
CardValue
u32 CardValue[52] static
Initial value:
= { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                             0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                             0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                             0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 }
Definition at line 62 of file poker.c.
Referenced by DisplayCard().
handstrs
char* handstrs[16] static
Initial value:
= { "high card",
                              "one pair",
                              "two pair",
                              "three of a kind",
                              "straight",
                              "flush",
                              "full house",
                              "four of a kind",
                              "straight flush",
                              "err",
                              "err",
                              "err",
                              "err",
                              "err",
                              "err",
                              "err" }
Definition at line 41 of file poker.c.
Referenced by set_handstr().
kickerstrs
char* kickerstrs[16] static
Initial value:
= { "", "kickers", "kicker",  "kickers",
                                "high", "high",    "full of", "kicker",
                                "high", "err",     "err",     "err",
                                "err",  "err",     "err",     "err" }
Definition at line 57 of file poker.c.
Referenced by set_handstr().