Bet: /root/bet/privatebet/payment.h File Reference
payment.h File Reference
#include "bet.h"
Functions
int32_t bet_dcv_pay (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars)
int32_t bet_dcv_create_invoice_request (struct privatebet_info *bet, int32_t playerid, int32_t amount)
int32_t bet_dcv_invoice_pay (struct privatebet_info *bet, struct privatebet_vars *vars, int playerid, int amount)
void bet_dcv_paymentloop (void *_ptr)
int32_t bet_player_create_invoice (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars, char *deckid)
int32_t bet_player_create_invoice_request (cJSON *argjson, struct privatebet_info *bet, int32_t amount)
int32_t bet_player_invoice_pay (cJSON *argjson, struct privatebet_info *bet, struct privatebet_vars *vars, int amount)
void bet_player_paymentloop (void *_ptr)
int32_t bet_player_invoice_request (cJSON *argjson, cJSON *actionResponse, struct privatebet_info *bet, int32_t amount)
Function Documentation
bet_dcv_create_invoice_request()
int32_t bet_dcv_create_invoice_request (struct privatebet_info * bet, int32_t playerid, int32_t amount)
Definition at line 25 of file payment.c.
References privatebet_info::pubsock.
Referenced by bet_dcv_invoice_pay().
bet_dcv_invoice_pay()
int32_t bet_dcv_invoice_pay (struct privatebet_info * bet, struct privatebet_vars * vars, int playerid, int amount)
Definition at line 51 of file payment.c.
References bet_dcv_create_invoice_request(), and bet_dcv_paymentloop().
Referenced by bet_evaluate_hand().
bet_dcv_pay()
int32_t bet_dcv_pay (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars)
Definition at line 75 of file payment.c.
References make_command().
Referenced by bet_dcv_paymentloop().
bet_dcv_paymentloop()
void bet_dcv_paymentloop (void * _ptr)
Definition at line 122 of file payment.c.
References bet_dcv_pay(), privatebet_info::pullsock, privatebet_info::pushsock, and privatebet_info::subsock.
Referenced by bet_dcv_invoice_pay().
bet_player_create_invoice()
int32_t bet_player_create_invoice (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars, char * deckid)
Definition at line 152 of file payment.c.
References make_command(), mchips_msatoshichips, privatebet_info::myplayerid, privatebet_vars::player_funds, and privatebet_info::pushsock.
Referenced by bet_player_backend().
bet_player_create_invoice_request()
int32_t bet_player_create_invoice_request (cJSON * argjson, struct privatebet_info * bet, int32_t amount)
Definition at line 215 of file payment.c.
References privatebet_info::myplayerid, and privatebet_info::pushsock.
Referenced by bet_player_invoice_pay().
bet_player_invoice_pay()
int32_t bet_player_invoice_pay (cJSON * argjson, struct privatebet_info * bet, struct privatebet_vars * vars, int amount)
Definition at line 271 of file payment.c.
References bet_player_create_invoice_request(), and bet_player_paymentloop().
Referenced by bet_player_big_blind(), and bet_player_small_blind().
bet_player_invoice_request()
int32_t bet_player_invoice_request (cJSON * argjson, cJSON * actionResponse, struct privatebet_info * bet, int32_t amount)
Definition at line 243 of file payment.c.
References privatebet_info::myplayerid, and privatebet_info::pushsock.
Referenced by bet_player_round_betting().
bet_player_paymentloop()
void bet_player_paymentloop (void * _ptr)
Definition at line 290 of file payment.c.
References ln_pay_invoice(), privatebet_info::pushsock, and privatebet_info::subsock.
Referenced by bet_player_invoice_pay().