Bet: privatebet/commands.h File Reference
commands.h File Reference
#include "bet.h"
Macros
#define arg_size 16384
#define tx_data_size 4196
#define ln_uri_length 200
Functions
int32_t bet_alloc_args (int argc, char ***argv)
void bet_dealloc_args (int argc, char ***argv)
int32_t chips_iswatchonly (char *address)
void chips_spend_multi_sig_address (char *address, double amount)
cJSON * chips_import_address (char *address)
char * chips_get_new_address ()
int chips_validate_address (char *address)
cJSON * chips_list_address_groupings ()
cJSON * chips_get_block_hash_from_height (int64_t block_height)
cJSON * chips_get_block_from_block_hash (char *block_hash_info)
cJSON * chips_get_block_from_block_height (int64_t block_height)
int32_t chips_if_tx_vin_of_tx (cJSON *txid, char *vin_tx_id)
cJSON * chips_find_parent_tx (int64_t block_height, char *vin_tx_id)
cJSON * chips_get_vin_from_tx (char *txid)
cJSON * validate_given_tx (int64_t block_height, char *txid)
cJSON * chips_transfer_funds (double amount, char *address)
cJSON * chips_send_raw_tx (cJSON *signed_tx)
cJSON * chips_sign_raw_tx_with_wallet (char *raw_tx)
int32_t chips_publish_multisig_tx (char *tx)
cJSON * chips_create_raw_tx (double amount, char *address)
int32_t chips_get_block_count ()
void check_ln_chips_sync ()
cJSON * bet_get_chips_ln_bal_info ()
double chips_get_balance ()
cJSON * bet_get_chips_ln_addr_info ()
cJSON * chips_add_multisig_address ()
cJSON * chips_add_multisig_address_from_list (int32_t threshold_value, cJSON *addr_list)
int32_t chips_check_if_tx_unspent (char *input_tx)
char * chips_get_block_hash_from_txid (char *txid)
int32_t chips_get_block_height_from_block_hash (char *block_hash)
cJSON * chips_create_tx_from_tx_list (char *to_addr, int32_t no_of_txs, char tx_ids[][100])
cJSON * chips_sign_msig_tx_of_table_id (char *ip, cJSON *raw_tx, char *table_id)
cJSON * chips_sign_msig_tx (char *ip, cJSON *raw_tx)
cJSON * chips_spend_msig_txs (char *to_addr, int no_of_txs, char tx_ids[][100])
cJSON * chips_get_raw_tx (char *tx)
cJSON * chips_decode_raw_tx (cJSON *raw_tx)
void chips_validate_tx (char *tx)
int32_t chips_extract_data (char *tx, char **rand_str)
cJSON * chips_create_raw_tx_with_data (double amount, char *address, char *data)
cJSON * chips_transfer_funds_with_data (double amount, char *address, char *data)
cJSON * chips_deposit_to_ln_wallet (double channel_chips)
double chips_get_balance_on_address_from_tx (char *address, char *tx)
char * chips_get_wallet_address ()
cJSON * chips_create_payout_tx (cJSON *payout_addr, int32_t no_of_txs, char tx_ids[][100], char *data)
int32_t chips_check_tx_exists_in_unspent (char *tx_id)
int32_t chips_check_tx_exists (char *tx_id)
int32_t run_command (int argc, char **argv)
int32_t make_command (int argc, char **argv, cJSON **argjson)
char * ln_get_new_address ()
int32_t ln_block_height ()
int32_t ln_listfunds ()
char * ln_get_uri (char **uri)
int32_t ln_connect_uri (char *uri)
cJSON * ln_fund_channel (char *channel_id, int32_t channel_fund_satoshi)
int32_t ln_pay (char *bolt11)
cJSON * ln_connect (char *id)
int32_t ln_check_if_address_isof_type (char *type)
void ln_check_peer_and_connect (char *id)
int32_t ln_get_channel_status (char *id)
int32_t ln_wait_for_tx_block_height (int32_t block_height)
int32_t ln_establish_channel (char *uri)
char * bet_git_version ()
Macro Definition Documentation
arg_size
#define arg_size 16384
Definition at line 3 of file commands.h.
ln_uri_length
#define ln_uri_length 200
Definition at line 5 of file commands.h.
tx_data_size
#define tx_data_size 4196
Definition at line 4 of file commands.h.
Function Documentation
bet_alloc_args()
int32_t bet_alloc_args (int argc, char *** argv)
Definition at line 35 of file commands.c.
References arg_size.
Referenced by bet_copy_args(), bet_game_info(), bet_git_version(), bet_player_process_game_info(), chips_add_multisig_address(), chips_check_if_tx_unspent(), chips_create_payout_tx(), chips_create_raw_tx(), chips_create_raw_tx_with_data(), chips_decode_raw_tx(), chips_deposit_to_ln_wallet(), chips_get_balance(), chips_get_balance_on_address_from_tx(), chips_get_block_count(), chips_get_block_hash_from_height(), chips_get_block_height_from_block_hash(), chips_get_new_address(), chips_get_vout_from_tx(), chips_get_wallet_address(), chips_import_address(), chips_iswatchonly(), chips_list_address_groupings(), chips_send_raw_tx(), chips_sign_raw_tx_with_wallet(), chips_validate_address(), ln_block_height(), ln_check_if_address_isof_type(), ln_check_peer_and_connect(), ln_connect(), ln_connect_uri(), ln_fund_channel(), ln_get_channel_status(), ln_get_uri(), ln_listfunds(), ln_pay(), and ln_wait_for_tx_block_height().
bet_dealloc_args()
void bet_dealloc_args (int argc, char *** argv)
Definition at line 50 of file commands.c.
Referenced by bet_game_info(), bet_git_version(), bet_player_process_game_info(), chips_add_multisig_address(), chips_add_multisig_address_from_list(), chips_check_if_tx_unspent(), chips_create_payout_tx(), chips_create_raw_tx(), chips_create_raw_tx_with_data(), chips_create_tx_from_tx_list(), chips_decode_raw_tx(), chips_deposit_to_ln_wallet(), chips_get_balance(), chips_get_block_count(), chips_get_block_from_block_hash(), chips_get_block_hash_from_height(), chips_get_block_hash_from_txid(), chips_get_block_height_from_block_hash(), chips_get_new_address(), chips_get_raw_tx(), chips_get_vin_from_tx(), chips_get_vout_from_tx(), chips_get_wallet_address(), chips_if_tx_vin_of_tx(), chips_import_address(), chips_iswatchonly(), chips_list_address_groupings(), chips_send_raw_tx(), chips_sign_raw_tx_with_wallet(), chips_validate_address(), ln_block_height(), ln_check_if_address_isof_type(), ln_check_peer_and_connect(), ln_connect(), ln_connect_uri(), ln_fund_channel(), ln_get_channel_status(), ln_get_new_address(), ln_get_uri(), ln_listfunds(), ln_pay(), and ln_wait_for_tx_block_height().
bet_get_chips_ln_addr_info()
cJSON* bet_get_chips_ln_addr_info ()
Definition at line 612 of file commands.c.
References chips_get_new_address(), and ln_get_new_address().
Referenced by bet_dcv_frontend(), and bet_player_frontend().
bet_get_chips_ln_bal_info()
cJSON* bet_get_chips_ln_bal_info ()
Definition at line 601 of file commands.c.
References chips_get_balance(), ln_listfunds(), and satoshis.
Referenced by bet_dcv_frontend(), and bet_player_frontend().
bet_git_version()
char* bet_git_version ()
Definition at line 1830 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by main().
check_ln_chips_sync()
void check_ln_chips_sync ()
Definition at line 582 of file commands.c.
References chips_get_block_count(), and ln_block_height().
Referenced by common_init().
chips_add_multisig_address()
cJSON* chips_add_multisig_address ()
Definition at line 639 of file commands.c.
References arg_size, bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), live_notaries, make_command(), no_of_notaries, notary_node_pubkeys, notary_status, and threshold_value.
Referenced by bet_compute_m_of_n_msig_addr().
chips_add_multisig_address_from_list()
cJSON* chips_add_multisig_address_from_list (int32_t threshold_value, cJSON * addr_list)
Definition at line 670 of file commands.c.
References arg_size, bet_copy_args(), bet_dealloc_args(), make_command(), and threshold_value.
Referenced by bet_cashier_backend_thrd().
chips_check_if_tx_unspent()
int32_t chips_check_if_tx_unspent (char * input_tx)
Definition at line 688 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), chips_check_tx_exists(), legacy_m_of_n_msig_addr, and run_command().
Referenced by bet_dcv_verify_tx().
chips_check_tx_exists()
int32_t chips_check_tx_exists (char * tx_id)
Definition at line 1303 of file commands.c.
References legacy_m_of_n_msig_addr.
Referenced by chips_check_if_tx_unspent().
chips_check_tx_exists_in_unspent()
int32_t chips_check_tx_exists_in_unspent (char * tx_id)
Definition at line 1266 of file commands.c.
Referenced by chips_create_tx_from_tx_list().
chips_create_payout_tx()
cJSON* chips_create_payout_tx (cJSON * payout_addr, int32_t no_of_txs, char tx_ids[][100], char * data)
Definition at line 1151 of file commands.c.
References arg_size, bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), bet_msg_cashier(), bet_run_query(), chips_get_balance_on_address_from_tx(), chips_get_vout_from_tx(), chips_spend_msig_tx(), chips_tx_fee, epsilon, legacy_m_of_n_msig_addr, make_command(), no_of_notaries, no_of_txs, notary_node_ips, notary_status, table_id, and tx_ids.
Referenced by bet_dcv_poker_winner().
chips_create_raw_tx()
cJSON* chips_create_raw_tx (double amount, char * address)
Definition at line 437 of file commands.c.
References arg_size, bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), chips_get_balance(), chips_tx_fee, make_command(), and multisigAddress.
Referenced by chips_spend_multi_sig_address(), and chips_transfer_funds().
chips_create_raw_tx_with_data()
cJSON* chips_create_raw_tx_with_data (double amount, char * address, char * data)
Definition at line 500 of file commands.c.
References arg_size, bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), chips_get_balance(), chips_tx_fee, make_command(), and multisigAddress.
Referenced by chips_transfer_funds_with_data().
chips_create_tx_from_tx_list()
cJSON* chips_create_tx_from_tx_list (char * to_addr, int32_t no_of_txs, char tx_ids[][100])
Definition at line 757 of file commands.c.
References arg_size, bet_copy_args(), bet_dealloc_args(), chips_check_tx_exists_in_unspent(), chips_decode_raw_tx(), chips_extract_data(), chips_get_raw_tx(), chips_tx_fee, hexstr_to_str(), make_command(), no_of_txs, player_info, tx_data_size, and tx_ids.
Referenced by bet_resolve_game_dispute(), bet_reverse_disputed_tx(), and chips_spend_msig_txs().
chips_decode_raw_tx()
cJSON* chips_decode_raw_tx (cJSON * raw_tx)
Definition at line 959 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by chips_create_tx_from_tx_list(), chips_extract_data(), and chips_validate_tx().
chips_deposit_to_ln_wallet()
cJSON* chips_deposit_to_ln_wallet (double channel_chips)
Definition at line 1025 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), chips_transfer_funds(), and make_command().
Referenced by ln_establish_channel().
chips_extract_data()
int32_t chips_extract_data (char * tx, char ** rand_str)
Definition at line 992 of file commands.c.
References chips_decode_raw_tx(), and chips_get_raw_tx().
Referenced by bet_dcv_verify_tx(), bet_process_dispute(), bet_show_fail_history(), bet_show_success_history(), and chips_create_tx_from_tx_list().
chips_find_parent_tx()
cJSON* chips_find_parent_tx (int64_t block_height, char * vin_tx_id)
Definition at line 279 of file commands.c.
References chips_get_block_count(), chips_get_block_from_block_height(), and chips_if_tx_vin_of_tx().
Referenced by validate_given_tx().
chips_get_balance()
double chips_get_balance ()
Definition at line 623 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_get_chips_ln_bal_info(), bet_player_handle_stack_info_resp(), bet_player_wallet_info(), bet_player_withdraw_request(), chips_create_raw_tx(), chips_create_raw_tx_with_data(), and ln_establish_channel().
chips_get_balance_on_address_from_tx()
double chips_get_balance_on_address_from_tx (char * address, char * tx)
Definition at line 1070 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_memset_args(), find_address_in_addresses(), and make_command().
Referenced by bet_dcv_poker_winner(), bet_dcv_process_tx(), and chips_create_payout_tx().
chips_get_block_count()
int32_t chips_get_block_count ()
Definition at line 565 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_dcv_verify_tx(), check_ln_chips_sync(), chips_find_parent_tx(), and validate_given_tx().
chips_get_block_from_block_hash()
cJSON* chips_get_block_from_block_hash (char * block_hash_info)
Definition at line 215 of file commands.c.
References bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by chips_get_block_from_block_height().
chips_get_block_from_block_height()
cJSON* chips_get_block_from_block_height (int64_t block_height)
Definition at line 229 of file commands.c.
References chips_get_block_from_block_hash(), and chips_get_block_hash_from_height().
Referenced by chips_find_parent_tx().
chips_get_block_hash_from_height()
cJSON* chips_get_block_hash_from_height (int64_t block_height)
Definition at line 195 of file commands.c.
References bet_alloc_args(), bet_dealloc_args(), and make_command().
Referenced by chips_get_block_from_block_height().
chips_get_block_hash_from_txid()
char* chips_get_block_hash_from_txid (char * txid)
Definition at line 706 of file commands.c.
References bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_player_handle_stack_info_resp(), ln_establish_channel(), and validate_given_tx().
chips_get_block_height_from_block_hash()
int32_t chips_get_block_height_from_block_hash (char * block_hash)
Definition at line 729 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_player_handle_stack_info_resp(), and ln_establish_channel().
chips_get_new_address()
char* chips_get_new_address ()
Definition at line 131 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_get_chips_ln_addr_info(), bet_player_handle_stack_info_resp(), bet_player_stack_info_req(), and chips_get_wallet_address().
chips_get_raw_tx()
cJSON* chips_get_raw_tx (char * tx)
Definition at line 939 of file commands.c.
References bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by chips_create_tx_from_tx_list(), chips_extract_data(), and chips_validate_tx().
chips_get_vin_from_tx()
cJSON* chips_get_vin_from_tx (char * txid)
Definition at line 305 of file commands.c.
References bet_copy_args(), bet_dealloc_args(), bet_memset_args(), and make_command().
Referenced by validate_given_tx().
chips_get_wallet_address()
char* chips_get_wallet_address ()
Definition at line 1099 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), chips_get_new_address(), chips_validate_address(), and make_command().
Referenced by bet_dcv_poker_winner(), bet_player_wallet_info(), and sqlite3_get_game_details().
chips_if_tx_vin_of_tx()
int32_t chips_if_tx_vin_of_tx (cJSON * txid, char * vin_tx_id)
Definition at line 243 of file commands.c.
References bet_copy_args(), bet_dealloc_args(), bet_memset_args(), and make_command().
Referenced by chips_find_parent_tx().
chips_import_address()
cJSON* chips_import_address (char * address)
Definition at line 116 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_compute_m_of_n_msig_addr(), bet_reverse_disputed_tx(), and chips_spend_multi_sig_address().
chips_iswatchonly()
int32_t chips_iswatchonly (char * address)
Definition at line 85 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_compute_m_of_n_msig_addr(), bet_reverse_disputed_tx(), and chips_spend_multi_sig_address().
chips_list_address_groupings()
cJSON* chips_list_address_groupings ()
Definition at line 164 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), chips_validate_address(), and make_command().
Referenced by bet_player_withdraw_request().
chips_publish_multisig_tx()
int32_t chips_publish_multisig_tx (char * tx)
Definition at line 411 of file commands.c.
References bet_dcv, is_signed, privatebet_info::numplayers, and privatebet_info::pubsock.
Referenced by bet_dcv_process_signed_raw_tx().
chips_send_raw_tx()
cJSON* chips_send_raw_tx (cJSON * signed_tx)
Definition at line 380 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_dcv_process_signed_raw_tx(), bet_resolve_game_dispute(), bet_reverse_disputed_tx(), chips_spend_msig_tx(), chips_spend_msig_txs(), chips_transfer_funds(), and chips_transfer_funds_with_data().
chips_sign_msig_tx()
cJSON* chips_sign_msig_tx (char * ip, cJSON * raw_tx)
Definition at line 846 of file commands.c.
References bet_msg_cashier_with_response_id(), table_id, and unique_id.
Referenced by bet_reverse_disputed_tx(), chips_spend_msig_tx(), and chips_spend_msig_txs().
chips_sign_msig_tx_of_table_id()
cJSON* chips_sign_msig_tx_of_table_id (char * ip, cJSON * raw_tx, char * table_id)
Definition at line 832 of file commands.c.
References bet_msg_cashier_with_response_id(), table_id, and unique_id.
Referenced by bet_resolve_game_dispute().
chips_sign_raw_tx_with_wallet()
cJSON* chips_sign_raw_tx_with_wallet (char * raw_tx)
Definition at line 396 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_cashier_process_raw_msig_tx(), bet_player_backend(), chips_transfer_funds(), and chips_transfer_funds_with_data().
chips_spend_msig_txs()
cJSON* chips_spend_msig_txs (char * to_addr, int no_of_txs, char tx_ids[][100])
Definition at line 860 of file commands.c.
References bet_check_cashiers_status(), chips_create_tx_from_tx_list(), chips_send_raw_tx(), chips_sign_msig_tx(), no_of_notaries, no_of_txs, notary_node_ips, notary_status, and tx_ids.
chips_spend_multi_sig_address()
void chips_spend_multi_sig_address (char * address, double amount)
Definition at line 104 of file commands.c.
References chips_create_raw_tx(), chips_import_address(), and chips_iswatchonly().
chips_transfer_funds()
cJSON* chips_transfer_funds (double amount, char * address)
Definition at line 369 of file commands.c.
References chips_create_raw_tx(), chips_send_raw_tx(), and chips_sign_raw_tx_with_wallet().
Referenced by bet_player_withdraw(), chips_deposit_to_ln_wallet(), and main().
chips_transfer_funds_with_data()
cJSON* chips_transfer_funds_with_data (double amount, char * address, char * data)
Definition at line 350 of file commands.c.
References arg_size, chips_create_raw_tx_with_data(), chips_send_raw_tx(), and chips_sign_raw_tx_with_wallet().
Referenced by bet_player_handle_stack_info_resp().
chips_validate_address()
int chips_validate_address (char * address)
Definition at line 146 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by chips_get_wallet_address(), and chips_list_address_groupings().
chips_validate_tx()
void chips_validate_tx (char * tx)
Definition at line 974 of file commands.c.
References chips_decode_raw_tx(), and chips_get_raw_tx().
ln_block_height()
int32_t ln_block_height ()
Definition at line 1491 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by check_ln_chips_sync().
ln_check_if_address_isof_type()
int32_t ln_check_if_address_isof_type (char * type)
Definition at line 1663 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_client_join_res().
ln_check_peer_and_connect()
void ln_check_peer_and_connect (char * id)
Definition at line 1695 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), ln_connect(), and make_command().
Referenced by bet_client_join_res().
ln_connect()
cJSON* ln_connect (char * id)
Definition at line 1646 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by ln_check_peer_and_connect(), and ln_establish_channel().
ln_connect_uri()
int32_t ln_connect_uri (char * uri)
Definition at line 1572 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), CHANNELD_AWAITING_LOCKIN, CHANNELD_NORMAL, ln_get_channel_status(), ln_uri_length, and make_command().
ln_establish_channel()
int32_t ln_establish_channel (char * uri)
Definition at line 1779 of file commands.c.
References channel_fund_satoshis, CHANNELD_AWAITING_LOCKIN, CHANNELD_NORMAL, chips_deposit_to_ln_wallet(), chips_get_balance(), chips_get_block_hash_from_txid(), chips_get_block_height_from_block_hash(), chips_tx_fee, ln_connect(), ln_fund_channel(), ln_get_channel_status(), ln_listfunds(), ln_uri_length, ln_wait_for_tx_block_height(), and satoshis.
Referenced by bet_client_join_res().
ln_fund_channel()
cJSON* ln_fund_channel (char * channel_id, int32_t channel_fund_satoshi)
Definition at line 1601 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by ln_establish_channel().
ln_get_channel_status()
int32_t ln_get_channel_status (char * id)
Definition at line 1726 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_award_winner(), bet_client_join_res(), bet_ln_check(), ln_connect_uri(), and ln_establish_channel().
ln_get_new_address()
char* ln_get_new_address ()
Definition at line 1476 of file commands.c.
References bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_get_chips_ln_addr_info().
ln_get_uri()
char* ln_get_uri (char ** uri)
Definition at line 1538 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_player_join_req().
ln_listfunds()
int32_t ln_listfunds ()
Definition at line 1507 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by bet_get_chips_ln_bal_info(), bet_player_backend(), and ln_establish_channel().
ln_pay()
int32_t ln_pay (char * bolt11)
Definition at line 1619 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
ln_wait_for_tx_block_height()
int32_t ln_wait_for_tx_block_height (int32_t block_height)
Definition at line 1752 of file commands.c.
References bet_alloc_args(), bet_copy_args(), bet_dealloc_args(), and make_command().
Referenced by ln_establish_channel().
make_command()
int32_t make_command (int argc, char ** argv, cJSON ** argjson)
Definition at line 1375 of file commands.c.
References chips_read_valid_unspent().
Referenced by bet_award_winner(), bet_client_join(), bet_create_betting_invoice(), bet_create_invoice(), bet_dcv_pay(), bet_find_channel_balance(), bet_git_version(), bet_player_betting_invoice(), bet_player_create_invoice(), bet_player_fundchannel(), bet_player_winner(), chips_add_multisig_address(), chips_add_multisig_address_from_list(), chips_create_payout_tx(), chips_create_raw_tx(), chips_create_raw_tx_with_data(), chips_create_tx_from_tx_list(), chips_decode_raw_tx(), chips_deposit_to_ln_wallet(), chips_get_balance(), chips_get_balance_on_address_from_tx(), chips_get_block_count(), chips_get_block_from_block_hash(), chips_get_block_hash_from_height(), chips_get_block_hash_from_txid(), chips_get_block_height_from_block_hash(), chips_get_new_address(), chips_get_raw_tx(), chips_get_vin_from_tx(), chips_get_vout_from_tx(), chips_get_wallet_address(), chips_if_tx_vin_of_tx(), chips_import_address(), chips_iswatchonly(), chips_list_address_groupings(), chips_send_raw_tx(), chips_sign_raw_tx_with_wallet(), chips_validate_address(), ln_block_height(), ln_check_if_address_isof_type(), ln_check_peer_and_connect(), ln_connect(), ln_connect_uri(), ln_fund_channel(), ln_get_channel_status(), ln_get_new_address(), ln_get_uri(), ln_listfunds(), ln_pay(), ln_pay_invoice(), and ln_wait_for_tx_block_height().
run_command()
int32_t run_command (int argc, char ** argv)
Definition at line 1343 of file commands.c.
Referenced by chips_check_if_tx_unspent().
validate_given_tx()
cJSON* validate_given_tx (int64_t block_height, char * txid)
Definition at line 331 of file commands.c.
References chips_find_parent_tx(), chips_get_block_count(), chips_get_block_hash_from_txid(), and chips_get_vin_from_tx().